import { jsPDF } from 'jspdf';
import type { MedicalRecord } from './medicalRecords';

const BRAND = {
  primary: '#F5A623',
  dark: '#1E293B',
  medium: '#475569',
  light: '#F1F5F9',
  white: '#FFFFFF',
  text: '#0F172A',
  muted: '#64748B',
  border: '#E2E8F0',
};

function formatDate(ts: any): string {
  if (!ts) return '';
  const d = ts.toDate ? ts.toDate() : new Date(ts);
  return d.toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
}

const TYPE_LABELS: Record<string, string> = {
  prescription: 'Prescription',
  vaccine: 'Vaccination Record',
  lab_result: 'Lab Result',
  surgery: 'Surgery Report',
  visit_note: 'Visit Note',
  other: 'Medical Record',
};

export function generateRecordPDF(record: MedicalRecord, petName: string): Blob {
  const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = 210;
  let y = 15;

  // Header bar
  pdf.setFillColor(BRAND.primary);
  pdf.rect(0, 0, pageW, 22, 'F');

  pdf.setTextColor(BRAND.white);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(16);
  pdf.text('Planet Animal Hospital', 14, 14);

  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Hospital & Wellness', 14, 19);

  y = 30;

  // Title
  pdf.setTextColor(BRAND.dark);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(18);
  pdf.text(TYPE_LABELS[record.type] || 'Medical Record', 14, y);
  y += 8;

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(BRAND.muted);
  pdf.text(`Generated by Planet Animal Hospital — ${new Date().toLocaleDateString('en-IN')}`, 14, y);
  y += 12;

  // Divider
  pdf.setDrawColor(BRAND.border);
  pdf.setLineWidth(0.5);
  pdf.line(14, y, pageW - 14, y);
  y += 10;

  // Pet & Record Info
  pdf.setFontSize(10);
  pdf.setTextColor(BRAND.dark);

  const leftX = 14;
  const rightX = 110;
  const colW = 90;

  pdf.setFont('helvetica', 'bold');
  pdf.text('Pet:', leftX, y);
  pdf.text('Record Title:', rightX, y);
  y += 5;

  pdf.setFont('helvetica', 'normal');
  pdf.text(petName, leftX, y);
  pdf.text(record.title, rightX, y);
  y += 6;

  pdf.setFont('helvetica', 'bold');
  pdf.text('Date:', leftX, y);
  pdf.text('Veterinarian:', rightX, y);
  y += 5;

  pdf.setFont('helvetica', 'normal');
  pdf.text(formatDate(record.date), leftX, y);
  pdf.text(record.vetName || 'Not specified', rightX, y);
  y += 6;

  pdf.setFont('helvetica', 'bold');
  pdf.text('Clinic:', leftX, y);
  pdf.text('Verified:', rightX, y);
  y += 5;

  pdf.setFont('helvetica', 'normal');
  pdf.text(record.clinicName || 'Not specified', leftX, y);
  pdf.text(record.verified ? 'Yes — confirmed by pet parent' : 'Pending verification', rightX, y);
  y += 6;

  if (record.followUpDate) {
    pdf.setFont('helvetica', 'bold');
    pdf.text('Follow-up:', leftX, y);
    y += 5;
    pdf.setFont('helvetica', 'normal');
    pdf.text(record.followUpDate, leftX, y);
    y += 6;
  }

  y += 6;
  pdf.setDrawColor(BRAND.border);
  pdf.line(14, y, pageW - 14, y);
  y += 10;

  // Medications Table
  if (record.medications && record.medications.length > 0) {
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(13);
    pdf.setTextColor(BRAND.primary);
    pdf.text('Medications', 14, y);
    y += 8;

    const colDefs = [
      { x: 14, w: 36, header: 'Name' },
      { x: 50, w: 28, header: 'Dosage' },
      { x: 78, w: 32, header: 'Frequency' },
      { x: 110, w: 28, header: 'Duration' },
      { x: 138, w: 58, header: 'Notes' },
    ];

    pdf.setFillColor(BRAND.primary);
    pdf.rect(14, y - 5, pageW - 28, 7, 'F');

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(8);
    pdf.setTextColor(BRAND.white);
    for (const col of colDefs) {
      pdf.text(col.header, col.x + 1, y);
    }
    y += 6;

    pdf.setTextColor(BRAND.text);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);

    for (const med of record.medications) {
      if (y > 270) {
        pdf.addPage();
        y = 20;
      }
      const vals = [med.name, med.dosage, med.frequency, med.duration, med.notes || ''];
      for (let i = 0; i < colDefs.length; i++) {
        const text = vals[i] || '';
        const maxW = colDefs[i].w - 2;
        const lines = pdf.splitTextToSize(text, maxW);
        pdf.text(lines as string[], colDefs[i].x + 1, y);
      }
      y += 7;
      pdf.setDrawColor(BRAND.border);
      pdf.setLineWidth(0.1);
      pdf.line(14, y - 2, pageW - 14, y - 2);
    }
    y += 6;
  }

  // Instructions
  if (record.instructions) {
    if (y > 240) { pdf.addPage(); y = 20; }
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(13);
    pdf.setTextColor(BRAND.primary);
    pdf.text('Instructions', 14, y);
    y += 8;

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9);
    pdf.setTextColor(BRAND.text);
    const instLines = pdf.splitTextToSize(record.instructions, pageW - 28);
    pdf.text(instLines, 14, y);
    y += (instLines.length * 5) + 8;
  }

  // Diagnosis
  if (record.diagnosis) {
    if (y > 250) { pdf.addPage(); y = 20; }
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(13);
    pdf.setTextColor(BRAND.primary);
    pdf.text('Diagnosis', 14, y);
    y += 8;

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9);
    pdf.setTextColor(BRAND.text);
    const diagLines = pdf.splitTextToSize(record.diagnosis, pageW - 28);
    pdf.text(diagLines, 14, y);
    y += (diagLines.length * 5) + 8;
  }

  // OCR Text
  if (record.ocrRawText) {
    if (y > 240) { pdf.addPage(); y = 20; }
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(13);
    pdf.setTextColor(BRAND.muted);
    pdf.text('OCR Reading', 14, y);
    y += 7;

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.setTextColor(BRAND.medium);
    const ocrLines = pdf.splitTextToSize(record.ocrRawText, pageW - 28);
    pdf.text(ocrLines, 14, y);
    y += (ocrLines.length * 4.5) + 6;
  }

  // Footer
  pdf.setDrawColor(BRAND.border);
  pdf.setLineWidth(0.5);
  pdf.line(14, 277, pageW - 14, 277);

  pdf.setFontSize(7);
  pdf.setTextColor(BRAND.muted);
  pdf.text('This document was generated by Planet Animal Hospital App. For verification, consult your veterinarian.', 14, 281);
  pdf.text('Planet Animal Hospital — Digital Medical Records', pageW - 14, 281, { align: 'right' });

  return pdf.output('blob');
}
