import {createClinicalHandler} from '../api/clinical';
import test from 'node:test';
import assert from 'node:assert/strict';
import {database,createCareHandler} from '../api/care';
import {createWalletHandler} from '../api/wallet';
import {createAssistantHandler} from '../api/assistant';
import {emptyState} from '../src/lib/care/domain';
if(!process.env.FIRESTORE_EMULATOR_HOST||!process.env.FIREBASE_AUTH_EMULATOR_HOST)throw Error('Emulators are required. This test cannot run against production.');
process.env.CARE_FIREBASE_PROJECT_ID='demo-planet-care';process.env.CARE_FIRESTORE_DATABASE_ID='(default)';delete process.env.CARE_FIREBASE_SERVICE_ACCOUNT_JSON;
const services=database();let providerCalls=0, failNext=false;let seenContext:any;
let clinicalCalls=0; const clinicalContent={summary:'Synthetic clinical draft for review.',sections:[{title:'Record completeness',observation:'Synthetic source requires clinician review.',basis:'recorded',sourceIds:['profile']}],suggestedCheckups:[],uncertainties:['Synthetic test only.']};
const handlers={clinical:createClinicalHandler(()=>services,async()=>{clinicalCalls++;return clinicalContent;}),care:createCareHandler(()=>services),wallet:createWalletHandler(()=>services),assistant:createAssistantHandler(()=>services,async(context)=>{providerCalls++;seenContext=context;if(failNext){failNext=false;throw Error("Synthetic provider unavailable");}return {summary:'The record has no follow-up date. Ask the hospital to clarify the recorded date.',discussionTopics:[],uncertainty:['Date not recorded.']};})};
const tokens:Record<string,string>={};
async function call(kind:keyof typeof handlers,user:string|undefined,body?:any,query='') {let text='';const res:any={setHeader(){},end(v:string){text=v;}};await handlers[kind]({method:body?'POST':'GET',url:'/api/'+kind+query,headers:user?{authorization:'Bearer '+tokens[user]}:{},body},res);return {status:res.statusCode,data:JSON.parse(text)};}
test('real Auth + Firestore: owner isolation, one completion award, no double spending, quotas and rule denial',async()=>{
 for(const [uid,role]of [['parent',null],['other',null],['staff','coordinator'],['vet','veterinarian'],['manager','manager']]){
  await services.auth.createUser({uid:uid!,email:uid+'@example.test',password:'Synthetic-only-123!'});
  if(role)await services.auth.setCustomUserClaims(uid!,{clinicId:'planet-animal',clinicRole:role});
  const r=await fetch('http://'+process.env.FIREBASE_AUTH_EMULATOR_HOST+'/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=fake-key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:uid+'@example.test',password:'Synthetic-only-123!',returnSecureToken:true})});tokens[uid!]=(await r.json()).idToken;
 }
 assert.equal((await call('wallet',undefined)).status,401);assert.equal((await call('wallet','other',undefined,'?ownerUid=parent')).status,403);
 await services.db.doc('careSettings/redemption').set({legacyCreditEnabled:true});await services.db.doc('users/parent').set({pawPoints:500,uid:'parent'});await services.db.doc('careAccounts/parent').set(emptyState('parent','Synthetic Pet'));
 assert.equal((await call('care','manager',{type:'configure',config:{version:'emulator-only',workflowName:'Synthetic test',rules:{fixture:{points:40,creditPaise:1000}}}})).status,200);
 const now=Date.now();assert.equal((await call('care','vet',{type:'approve',ownerUid:'parent',petId:'primary',id:'step',title:'Synthetic follow-up',instructions:'Recorded test instructions',sourceRef:'synthetic-source',windowStart:null,dueAt:null,reminderAt:null,ruleId:'fixture'})).status,200);
 assert.equal((await call('care','parent',{type:'book',petId:'primary',milestoneId:'step',requestedFor:now+86400000})).status,200);
 assert.equal((await call('care','staff',{type:'confirmBooking',ownerUid:'parent',petId:'primary',milestoneId:'step',scheduledAt:now+86400000,reference:'synthetic-booking'})).status,200);
 assert.equal((await call('wallet','parent')).data.pendingPoints,40);
 const completion={type:'complete',ownerUid:'parent',petId:'primary',milestoneId:'step',completedAt:Date.now(),evidence:'synthetic-service'};
 const completed=await Promise.all(Array.from({length:12},()=>call('care','staff',completion)));assert.ok(completed.every(r=>r.status===200),JSON.stringify(completed));
 let w=(await call('wallet','parent')).data;assert.equal(w.wallet.points,40);assert.equal(w.pendingPoints,0);assert.equal(w.entries.filter((e:any)=>e.type==='earn').length,1);assert.equal(w.legacyPoints,500);
 assert.equal((await call('wallet','parent',{type:'reconcileLegacy',expectedPoints:500})).status,403);assert.equal((await call('wallet','manager',{type:'reconcileLegacy',ownerUid:'parent',expectedPoints:499})).status,409);
 assert.equal((await call('wallet','manager',{type:'reconcileLegacy',ownerUid:'parent',expectedPoints:500})).data.wallet.points,540);
 assert.equal((await call('wallet','manager',{type:'reconcileLegacy',ownerUid:'parent',expectedPoints:500})).data.wallet.points,540);
 const invoice=(await call('wallet','staff',{type:'registerInvoice',ownerUid:'parent',reference:'synthetic-invoice',eligiblePaise:100000})).data.invoiceId;
 const reserved=await Promise.all(['r1','r2'].map(id=>call('wallet','parent',{type:'reserve',id,invoiceId:invoice,points:300})));assert.equal(reserved.filter(r=>r.status===200).length,1);const rid=reserved.find(r=>r.status===200)!.data.reservation.id;
 assert.equal((await call('wallet','parent',{type:'apply',id:rid,billingReference:'synthetic-adjustment'})).status,403);
 const applied=await Promise.all(Array.from({length:10},()=>call('wallet','staff',{type:'apply',ownerUid:'parent',id:rid,billingReference:'synthetic-adjustment'})));assert.ok(applied.every(r=>r.status===200));assert.equal((await call('wallet','parent')).data.wallet.points,240);
 await call('wallet','staff',{type:'reverse',ownerUid:'parent',id:rid,billingReference:'synthetic-reversal'});await call('wallet','staff',{type:'reverse',ownerUid:'parent',id:rid,billingReference:'synthetic-reversal'});assert.equal((await call('wallet','parent')).data.wallet.points,540);
 const question={requestId:'question-1',petId:'primary',agent:'pritpawl',prompt:'Which record details are missing?',consent:true,adult:true};
 const answers=await Promise.all(Array.from({length:8},()=>call('assistant','parent',question)));assert.equal(providerCalls,1);assert.ok(answers.some(r=>r.status===200),JSON.stringify(answers));assert.equal((await call('assistant','parent',question)).data.cached,true);
 assert.equal((await call('assistant','parent',{...question,prompt:'changed'})).status,409);
 const usageRef=services.db.doc('careAssistantUsage/parent');
 const recordBefore=(await services.db.doc('careAccounts/parent').get()).data()!;
 assert.equal(seenContext.recordedInstructions[0].instructions,recordBefore.milestones[0].instructions);
 failNext=true;await usageRef.update({activeUntil:0,lastAt:0});
 const retryQuestion={...question,requestId:'question-retry'};
 assert.equal((await call('assistant','parent',retryQuestion)).status,503);
 const dailyAfterFailure=(await usageRef.get()).data()!.daily;
 await usageRef.update({activeUntil:0,lastAt:0});
 const retried=await call('assistant','parent',retryQuestion);assert.equal(retried.status,200);assert.match(retried.data.draft.summary,/follow-up date/);
 assert.equal((await usageRef.get()).data()!.daily,dailyAfterFailure);
 assert.deepEqual((await services.db.doc('careAccounts/parent').get()).data(),recordBefore);
 const changedRecord=structuredClone(recordBefore);changedRecord.milestones[0].instructions='Updated synthetic recorded instructions';
 await services.db.doc('careAccounts/parent').set(changedRecord);
 assert.equal((await call('assistant','parent',retryQuestion)).status,409);
 await usageRef.update({daily:5,monthly:20,activeUntil:0,lastAt:0});assert.equal((await call('assistant','parent',{...question,requestId:'question-2'})).status,429);
 assert.equal((await call('wallet','staff',{type:'reverseEarn',ownerUid:'parent',entryId:'care-step',billingReference:'synthetic-service-refund'})).status,200);
 assert.equal((await call('wallet','staff',{type:'reverseEarn',ownerUid:'parent',entryId:'care-step',billingReference:'synthetic-service-refund'})).status,200);
 assert.equal((await call('wallet','parent')).data.wallet.points,500);
 const subscription={type:'verifySubscription',ownerUid:'parent',plan:'prestige',status:'active',startsAt:now-1000,endsAt:now+86400000,paymentReference:'synthetic-payment'};
 assert.equal((await call('wallet','parent',subscription)).status,403);
 assert.equal((await call('wallet','manager',subscription)).status,200);
 assert.equal((await call('wallet','manager',{...subscription,endsAt:now+2*86400000})).status,409);
 const expiryInvoice=(await call('wallet','staff',{type:'registerInvoice',ownerUid:'parent',reference:'expiry-invoice',eligiblePaise:100000})).data.invoiceId;
 await call('wallet','parent',{type:'reserve',id:'expiry',invoiceId:expiryInvoice,points:100});
 await services.db.doc('careWallets/parent/reservations/expiry').update({expiresAt:Date.now()-1});
 assert.equal((await call('wallet','parent')).data.wallet.reservedPoints,0);
 assert.equal((await services.db.doc('careWallets/parent/reservations/expiry').get()).data()!.status,'released');
 await call('care','vet',{type:'approve',ownerUid:'parent',petId:'primary',id:'step2',title:'Synthetic second follow-up',instructions:'Recorded test instruction',sourceRef:'synthetic-source2',windowStart:null,dueAt:null,reminderAt:null,ruleId:'fixture'});
 await call('care','staff',{type:'complete',ownerUid:'parent',petId:'primary',milestoneId:'step2',completedAt:Date.now(),evidence:'synthetic-service2'});
 const beforeSpend=(await call('wallet','parent')).data.wallet.points;
 const spendInvoice=(await call('wallet','staff',{type:'registerInvoice',ownerUid:'parent',reference:'spend-invoice',eligiblePaise:1000000})).data.invoiceId;
 await call('wallet','parent',{type:'reserve',id:'spend',invoiceId:spendInvoice,points:beforeSpend});
 await call('wallet','staff',{type:'apply',ownerUid:'parent',id:'spend',billingReference:'spend-adjustment'});
 assert.equal((await call('wallet','staff',{type:'reverseEarn',ownerUid:'parent',entryId:'care-step2',billingReference:'service2-refund'})).data.wallet.reconciliationRequired,true);
 await call('wallet','staff',{type:'reverse',ownerUid:'parent',id:'spend',billingReference:'spend-reversal'});
 assert.equal((await call('wallet','manager',{type:'settleRefund',ownerUid:'parent',id:'refund-care-step2'})).data.wallet.points,500);
 assert.equal((await call('wallet','parent')).data.wallet.reconciliationRequired,false);
 const policyBody={type:'configureRedemption',policy:{version:'synthetic-whole-bill',basis:'entire-bill',status:'active',tiers:[{id:'fixture',points:300,percent:10}],confirmCommercialApproval:true}};
 assert.equal((await call('wallet','parent',policyBody)).status,403);assert.equal((await call('wallet','manager',policyBody)).status,200);
 const wholeInvoice=(await call('wallet','staff',{type:'registerInvoice',ownerUid:'parent',reference:'whole-invoice',eligiblePaise:10000,totalPaise:200000})).data.invoiceId;
 const wholeRequest={type:'reserveTier',id:'whole-reserve',invoiceId:wholeInvoice,tierId:'fixture'};
 const whole=await Promise.all(Array.from({length:8},()=>call('wallet','parent',wholeRequest)));assert.ok(whole.every(r=>r.status===200));assert.equal(whole[0].data.reservation.paise,20000);
 assert.equal((await call('wallet','staff',{type:'apply',ownerUid:'parent',id:'whole-reserve',billingReference:'whole-adjustment'})).status,200);
 assert.equal((await call('wallet','parent')).data.wallet.points,200);
 assert.equal((await call('wallet','parent',{type:'reserve',id:'old-credit',invoiceId:wholeInvoice,points:1})).status,409);
 const clinicalQuery='?petId=primary';
 assert.equal((await call('clinical',undefined,undefined,clinicalQuery)).status,401);
 assert.equal((await call('clinical','other',undefined,'?ownerUid=parent&petId=primary')).status,403);
 const clinicalRequest={action:'generate',petId:'primary',requestId:'clinical-fixture',consent:true,adult:true};
 const clinicalResults=await Promise.all(Array.from({length:8},()=>call('clinical','parent',clinicalRequest)));
 assert.equal(clinicalCalls,1);assert.ok(clinicalResults.some(r=>r.status===202));
 assert.equal((await call('clinical','parent',undefined,clinicalQuery)).data.analyses[0].content,undefined);
 assert.equal((await call('clinical','staff',undefined,'?ownerUid=parent&petId=primary')).data.analyses[0].content,undefined);
 const clinicalDraft=(await call('clinical','vet',undefined,'?ownerUid=parent&petId=primary')).data.analyses[0];
 const clinicalApproval={action:'approve',ownerUid:'parent',petId:'primary',analysisId:clinicalDraft.id,revision:clinicalDraft.revision,content:{...clinicalContent,summary:'Synthetic veterinarian-edited summary.'},note:'Synthetic emulator review only.'};
 assert.equal((await call('clinical','parent',clinicalApproval)).status,403);
 assert.equal((await call('clinical','vet',clinicalApproval)).status,200);
 assert.equal((await call('clinical','parent',undefined,clinicalQuery)).data.analyses[0].content.summary,'Synthetic veterinarian-edited summary.');
 const source=(await services.db.doc('careAccounts/parent').get()).data()!;source.milestones[0].instructions='Changed synthetic source after approval';await services.db.doc('careAccounts/parent').set(source);
 assert.equal((await call('clinical','parent',undefined,clinicalQuery)).data.analyses[0].content,undefined);
 assert.equal((await call('wallet','parent')).data.wallet.points,200);
 const clinicalForbidden=await fetch('http://'+process.env.FIRESTORE_EMULATOR_HOST+'/v1/projects/demo-planet-care/databases/(default)/documents/careClinical/parent/pets/primary',{headers:{Authorization:'Bearer '+tokens.parent}});assert.equal(clinicalForbidden.status,403);
 const forbidden=await fetch('http://'+process.env.FIRESTORE_EMULATOR_HOST+'/v1/projects/demo-planet-care/databases/(default)/documents/careWallets/parent',{headers:{Authorization:'Bearer '+tokens.parent}});assert.equal(forbidden.status,403);
 console.log('Verified real emulator: 12 concurrent completions -> 1 award; competing reservations -> 1; 10 applies -> 1 debit; cached assistant -> 1 provider call; cross-owner and direct financial access denied.');
});
