import React, { useState, useEffect } from 'react';
import { Sparkles, ArrowRight, Loader2, RefreshCw, Clock, Utensils, ShieldCheck, HeartPulse, Lock } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { usePetProfile } from '../hooks/usePetProfile';

// --- MOCK API FOR LONGEVITY TOOL ---
const generateRoadmap = async (formData: any) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const preventativeCare = ["Regular cardiovascular screening given the breed profile.", "Bi-annual orthopedic assessments."];
      if (formData.surgicalHistory) {
        preventativeCare.push(`Monitor recovery and mobility based on history of: ${formData.surgicalHistory}`);
      }

      resolve({
        introduction: `Based on the profile of a ${formData.age}-year-old ${formData.breed}, here is a comprehensive health and longevity plan tailored for ${formData.name}.`,
        timeline: [
          { ageRange: "Immediate (Months 1-3)", focusArea: "Baseline Health & Prevention", actionItems: ["Schedule a comprehensive senior blood panel.", "Begin joint supplement integration.", `Monitor for signs related to ${formData.issues || 'general age-related wear'}.`] },
          { ageRange: "Mid-Term (Months 3-12)", focusArea: "Diet & Dental", actionItems: ["Transition to a breed-specific diet formula.", "Book a dental evaluation to prevent periodontal disease."] },
          { ageRange: "Long-Term (1-3 Years)", focusArea: "Mobility & Comfort", actionItems: ["Bi-annual wellness checks.", "Maintain lean muscle mass through controlled aquatic therapy."] }
        ],
        dietaryAdvice: ["Incorporate Omega-3 fatty acids for joint and cognitive health.", "Ensure strict portion control to maintain an ideal body condition score."],
        preventativeCare: preventativeCare,
        conclusion: `By staying proactive with this roadmap, you are giving ${formData.name} the best chance at a long, healthy, and happy life.`
      });
    }, 1500);
  });
};

export default function Roadmap() {
  const navigate = useNavigate();
  const { profile } = usePetProfile();
  
  const isProfileIncomplete = !profile.name || !profile.breed || !profile.weight;

  const [formData, setFormData] = useState({ 
    name: profile.name || '', 
    species: 'Dog', 
    breed: profile.breed || '', 
    age: profile.age || '5', 
    issues: profile.healthHistory || '',
    surgicalHistory: profile.surgicalHistory || ''
  });
  const [loading, setLoading] = useState(false);
  const [roadmap, setRoadmap] = useState<any>(null);
  const [error, setError] = useState('');
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  useEffect(() => {
    if (!isProfileIncomplete && !roadmap && !loading && !hasAutoGenerated) {
      const autoGenerate = async () => {
        setLoading(true);
        setHasAutoGenerated(true);
        try {
          setRoadmap(await generateRoadmap(formData));
        } catch (err) {
          setError('Failed to generate roadmap.');
        } finally {
          setLoading(false);
        }
      };
      autoGenerate();
    }
  }, [isProfileIncomplete, roadmap, loading, hasAutoGenerated, formData]);

  const handleInputChange = (e: any) => setFormData(prev => ({ ...prev, [e.target.name]: e.target.value }));

  const handleSubmit = async (e: any) => {
    e.preventDefault();
    if (!formData.name || !formData.breed || !formData.age) return setError('Please fill in Name, Breed, and Age.');
    
    setError('');
    setLoading(true);
    
    try {
      setRoadmap(await generateRoadmap(formData));
    } catch (err) {
      setError('Failed to generate roadmap.');
    } finally {
      setLoading(false);
    }
  };

  const resetForm = () => {
    setRoadmap(null);
    setFormData({ 
      name: profile.name || '', 
      species: 'Dog', 
      breed: profile.breed || '', 
      age: profile.age || '5', 
      issues: profile.healthHistory || '',
      surgicalHistory: profile.surgicalHistory || ''
    });
  };

  if (isProfileIncomplete) {
    return (
      <div className="h-full flex flex-col items-center justify-center p-6 mb-32 min-h-[600px]">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white/20 backdrop-blur-2xl border border-white/30 shadow-[0_8px_32px_rgba(0,0,0,0.1)] rounded-[2rem] p-10 max-w-md w-full text-center flex flex-col items-center"
        >
          <div className="w-24 h-24 bg-yellow-400/20 rounded-full flex items-center justify-center mb-6 shadow-[0_0_30px_rgba(250,204,21,0.3)] border border-yellow-300/50">
            <Lock className="w-10 h-10 text-yellow-600" />
          </div>
          <h2 className="text-2xl font-black text-slate-900 mb-3">Profile Incomplete</h2>
          <p className="text-slate-700 font-medium mb-8 leading-relaxed">
            A complete profile is required to unlock the personalized Longevity Roadmap for your pet.
          </p>
          <button 
            onClick={() => navigate('/settings')}
            className="w-full bg-gradient-to-r from-yellow-400 to-yellow-500 text-yellow-900 py-4 rounded-xl font-bold shadow-[0_0_20px_rgba(250,204,21,0.4)] hover:scale-[1.02] active:scale-95 transition-all"
          >
            Update Profile
          </button>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col bg-white/10 backdrop-blur-3xl border border-white/30 overflow-hidden shadow-[0_8px_32px_rgba(0,0,0,0.1)] min-h-[600px] max-w-2xl mx-auto rounded-[2rem] m-6 mb-32">
      <AnimatePresence mode="wait">
        {!roadmap ? (
          <motion.div key="form" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="p-8 sm:p-10 flex-1 flex flex-col">
            <div className="flex items-center gap-4 mb-8">
              <div className="bg-planet-yellow p-3 rounded-xl shadow-sm">
                <Sparkles className="w-6 h-6 text-black" />
              </div>
              <div>
                <h3 className="text-xl font-black text-slate-900">Longevity Roadmap</h3>
                <p className="text-slate-500 text-sm font-medium">Personalized health timeline</p>
              </div>
            </div>
            
            {error && (
              <div className="mb-6 p-3 bg-red-500/20 text-red-700 backdrop-blur-md border border-red-500/30 rounded-lg text-sm font-medium">
                {error}
              </div>
            )}
            
            <form onSubmit={handleSubmit} className="flex-1 flex flex-col space-y-5">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Pet Name</label>
                  <input type="text" name="name" value={formData.name} onChange={handleInputChange} placeholder="e.g. Max" className="w-full px-4 py-3 rounded-xl border border-white/40 focus:ring-2 focus:ring-yellow-400 focus:bg-white/60 outline-none bg-white/40 backdrop-blur-md text-slate-900 placeholder:text-slate-400 transition-all shadow-sm" />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Species</label>
                  <select name="species" value={formData.species} onChange={handleInputChange} className="w-full px-4 py-3 rounded-xl border border-white/40 focus:ring-2 focus:ring-yellow-400 focus:bg-white/60 outline-none bg-white/40 backdrop-blur-md text-slate-900 transition-all shadow-sm">
                    <option>Dog</option>
                    <option>Cat</option>
                    <option>Other</option>
                  </select>
                </div>
              </div>
              
              <div>
                <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Breed</label>
                <input type="text" name="breed" value={formData.breed} onChange={handleInputChange} placeholder="e.g. American Bully" className="w-full px-4 py-3 rounded-xl border border-white/40 focus:ring-2 focus:ring-yellow-400 focus:bg-white/60 outline-none bg-white/40 backdrop-blur-md text-slate-900 placeholder:text-slate-400 transition-all shadow-sm" />
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Age (Years)</label>
                  <input type="number" name="age" value={formData.age} onChange={handleInputChange} placeholder="e.g. 5" min="0" step="0.1" className="w-full px-4 py-3 rounded-xl border border-white/40 focus:ring-2 focus:ring-yellow-400 focus:bg-white/60 outline-none bg-white/40 backdrop-blur-md text-slate-900 placeholder:text-slate-400 transition-all shadow-sm" />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2">Known Issues</label>
                  <input type="text" name="issues" value={formData.issues} onChange={handleInputChange} placeholder="e.g. Joint pain" className="w-full px-4 py-3 rounded-xl border border-white/40 focus:ring-2 focus:ring-yellow-400 focus:bg-white/60 outline-none bg-white/40 backdrop-blur-md text-slate-900 placeholder:text-slate-400 transition-all shadow-sm" />
                </div>
              </div>
              
              <button type="submit" disabled={loading} className="mt-auto w-full bg-gradient-to-r from-yellow-400 to-yellow-500 text-yellow-900 py-4 rounded-xl font-bold flex justify-center items-center gap-2 shadow-[0_0_20px_rgba(250,204,21,0.4)] hover:scale-[1.02] active:scale-95 disabled:opacity-70 disabled:hover:scale-100 transition-all">
                {loading ? (
                  <>
                    <Loader2 className="animate-spin w-5 h-5" /> Analyzing...
                  </>
                ) : (
                  <>
                    Generate Profile <ArrowRight className="w-5 h-5" />
                  </>
                )}
              </button>
            </form>
          </motion.div>
        ) : (
          <motion.div key="results" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="p-8 flex-1 overflow-y-auto flex flex-col gap-6 hide-scrollbar">
            {/* Header */}
            <div className="flex justify-between items-start border-b border-white/30 pb-4">
              <div>
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-yellow-400/20 text-yellow-800 text-xs font-bold mb-2 border border-yellow-300/50 shadow-sm">
                  <Sparkles className="w-3 h-3" /> Roadmap Generated
                </div>
                <h2 className="text-2xl font-black text-slate-900">{formData.name}'s Plan</h2>
              </div>
              <button onClick={resetForm} className="p-2 text-slate-500 hover:text-slate-900 bg-white/40 backdrop-blur-md border border-white/40 rounded-full hover:bg-white/60 transition-all shadow-sm" title="Start Over">
                <RefreshCw size={18} />
              </button>
            </div>
            
            <p className="text-sm text-slate-700 bg-white/40 backdrop-blur-lg border border-white/50 p-4 rounded-xl leading-relaxed shadow-sm">
              {roadmap.introduction}
            </p>
            
            {/* Timeline */}
            <div>
              <h4 className="font-bold flex items-center gap-2 mb-4 text-slate-900">
                <Clock size={18} className="text-blue-500" /> Health Timeline
              </h4>
              <div className="space-y-4">
                {roadmap.timeline.map((item: any, i: number) => (
                  <div key={i} className="bg-white/40 backdrop-blur-lg border border-white/50 p-5 rounded-xl shadow-sm">
                    <span className="text-xs font-bold text-blue-600 uppercase tracking-wide">{item.ageRange}</span>
                    <h5 className="font-bold text-base mt-1 mb-3 text-slate-900">{item.focusArea}</h5>
                    <ul className="text-sm text-slate-700 space-y-2">
                      {item.actionItems.map((act: string, j: number) => (
                        <li key={j} className="flex items-start gap-2 leading-relaxed">
                          <div className="w-1.5 h-1.5 bg-blue-400 rounded-full mt-1.5 shrink-0" />
                          {act}
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            </div>
            
            {/* Diet & Care grids */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="bg-white/40 backdrop-blur-lg border border-white/50 p-5 rounded-xl shadow-sm">
                <h4 className="font-bold flex items-center gap-2 mb-3 text-green-700">
                  <Utensils size={18} /> Diet & Nutrition
                </h4>
                <ul className="text-sm text-slate-700 space-y-2">
                  {roadmap.dietaryAdvice.map((adv: string, i: number) => (
                    <li key={i} className="flex items-start gap-2">
                      <ShieldCheck className="w-4 h-4 mt-0.5 shrink-0 opacity-70 text-green-600" />
                      <span className="leading-relaxed">{adv}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <div className="bg-white/40 backdrop-blur-lg border border-white/50 p-5 rounded-xl shadow-sm">
                <h4 className="font-bold flex items-center gap-2 mb-3 text-purple-700">
                  <HeartPulse size={18} /> Preventative Care
                </h4>
                <ul className="text-sm text-slate-700 space-y-2">
                  {roadmap.preventativeCare.map((care: string, i: number) => (
                    <li key={i} className="flex items-start gap-2">
                      <HeartPulse className="w-4 h-4 mt-0.5 shrink-0 opacity-70 text-purple-600" />
                      <span className="leading-relaxed">{care}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
