import React, { useState, useEffect } from 'react';
import { Sparkles, ArrowRight, Loader2, RefreshCw, Clock, Utensils, ShieldCheck, HeartPulse, Lock } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { usePetProfile } from '../hooks/usePetProfile';

// --- MOCK API FOR LONGEVITY TOOL ---
const generateRoadmap = async (formData: any) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const preventativeCare = ["Regular cardiovascular screening given the breed profile.", "Bi-annual orthopedic assessments."];
      if (formData.surgicalHistory) {
        preventativeCare.push(`Monitor recovery and mobility based on history of: ${formData.surgicalHistory}`);
      }

      resolve({
        introduction: `Based on the profile of a ${formData.age}-year-old ${formData.breed}, here is a comprehensive health and longevity plan tailored for ${formData.name}.`,
        timeline: [
          { ageRange: "Immediate (Months 1-3)", focusArea: "Baseline Health & Prevention", actionItems: ["Schedule a comprehensive senior blood panel.", "Begin joint supplement integration.", `Monitor for signs related to ${formData.issues || 'general age-related wear'}.`] },
          { ageRange: "Mid-Term (Months 3-12)", focusArea: "Diet & Dental", actionItems: ["Transition to a breed-specific diet formula.", "Book a dental evaluation to prevent periodontal disease."] },
          { ageRange: "Long-Term (1-3 Years)", focusArea: "Mobility & Comfort", actionItems: ["Bi-annual wellness checks.", "Maintain lean muscle mass through controlled aquatic therapy."] }
        ],
        dietaryAdvice: ["Incorporate Omega-3 fatty acids for joint and cognitive health.", "Ensure strict portion control to maintain an ideal body condition score."],
        preventativeCare: preventativeCare,
        conclusion: `By staying proactive with this roadmap, you are giving ${formData.name} the best chance at a long, healthy, and happy life.`
      });
    }, 1500);
  });
};

export default function Roadmap() {
  const navigate = useNavigate();
  const { profile } = usePetProfile();
  
  const isProfileIncomplete = !profile.name || !profile.breed || !profile.weight;

  const [formData, setFormData] = useState({ 
    name: profile.name || '', 
    species: 'Dog', 
    breed: profile.breed || '', 
    age: profile.age || '5', 
    issues: profile.healthHistory || '',
    surgicalHistory: profile.surgicalHistory || ''
  });
  const [loading, setLoading] = useState(false);
  const [roadmap, setRoadmap] = useState<any>(null);
  const [error, setError] = useState('');
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [isInitialLoading, setIsInitialLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsInitialLoading(false);
    }, 2800);
    return () => clearTimeout(timer);
  }, []);

  useEffect(() => {
    if (!isProfileIncomplete && !roadmap && !loading && !hasAutoGenerated) {
      const autoGenerate = async () => {
        setLoading(true);
        setHasAutoGenerated(true);
        try {
          setRoadmap(await generateRoadmap(formData));
        } catch (err) {
          setError('Failed to generate roadmap.');
        } finally {
          setLoading(false);
        }
      };
      autoGenerate();
    }
  }, [isProfileIncomplete, roadmap, loading, hasAutoGenerated, formData]);

  const handleInputChange = (e: any) => setFormData(prev => ({ ...prev, [e.target.name]: e.target.value }));

  const handleSubmit = async (e: any) => {
    e.preventDefault();
    if (!formData.name || !formData.breed || !formData.age) return setError('Please fill in Name, Breed, and Age.');
    
    setError('');
    setLoading(true);
    
    try {
      setRoadmap(await generateRoadmap(formData));
    } catch (err) {
      setError('Failed to generate roadmap.');
    } finally {
      setLoading(false);
    }
  };

  const resetForm = () => {
    setRoadmap(null);
    setFormData({ 
      name: profile.name || '', 
      species: 'Dog', 
      breed: profile.breed || '', 
      age: profile.age || '5', 
      issues: profile.healthHistory || '',
      surgicalHistory: profile.surgicalHistory || ''
    });
  };

  if (isProfileIncomplete) {
    return (
      <div className="h-full w-full flex flex-col items-center justify-center p-6 pb-32">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="relative z-10 bg-white/80 dark:bg-white/[0.03] backdrop-blur-xl dark:backdrop-blur-[24px] border border-slate-200 dark:border-white/[0.08] shadow-sm dark:shadow-[inset_0_1px_1px_rgba(255,255,255,0.05),0_8px_32px_rgba(0,0,0,0.4)] rounded-[2rem] p-10 max-w-md w-full text-center flex flex-col items-center"
        >
          <div className="w-24 h-24 bg-[#fec708]/20 rounded-full flex items-center justify-center mb-6 shadow-[0_0_30px_rgba(254,199,8,0.3)] border border-[#fec708]/50">
            <Lock className="w-10 h-10 text-[#fec708]" />
          </div>
          <h2 className="text-2xl font-black text-slate-900 dark:text-white mb-3">Profile Incomplete</h2>
          <p className="text-slate-600 dark:text-white/80 font-medium mb-8 leading-relaxed">
            A complete profile is required to unlock the personalized Longevity Roadmap for your pet.
          </p>
          <button 
            onClick={() => navigate('/settings')}
            className="w-full bg-gradient-to-r from-[#fec708] to-[#fec708] text-black py-4 rounded-xl font-bold shadow-[0_0_20px_rgba(254,199,8,0.4)] hover:scale-[1.02] active:scale-95 transition-all"
          >
            Update Profile
          </button>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="h-full w-full flex flex-col pb-32">
      <AnimatePresence mode="wait">
        {isInitialLoading ? (
          <motion.div
            key="loading-overlay"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0, transition: { duration: 0.5 } }}
            className="absolute inset-0 z-50 flex flex-col items-center justify-center bg-slate-50 dark:bg-[#020d0b]"
          >
            <div className="flex gap-3 mb-6">
              {[
                { color: '#4285F4', delay: 0 },
                { color: '#EA4335', delay: 0.15 },
                { color: '#FBBC05', delay: 0.3 },
                { color: '#34A853', delay: 0.45 },
              ].map((dot, i) => (
                <motion.div
                  key={i}
                  className="w-4 h-4 rounded-full shadow-sm"
                  style={{ backgroundColor: dot.color }}
                  animate={{
                    y: [0, -15, 0],
                    scale: [1, 1.1, 1],
                  }}
                  transition={{
                    duration: 1,
                    repeat: Infinity,
                    ease: "easeInOut",
                    delay: dot.delay,
                  }}
                />
              ))}
            </div>
            <motion.h2 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5, duration: 0.8 }}
              className="text-lg font-medium text-[#fec708] tracking-wide font-sans drop-shadow-[0_0_12px_rgba(254,199,8,0.5)]"
            >
              Roadmap powered by <span className="font-black">Google</span>
            </motion.h2>
          </motion.div>
        ) : (
          <motion.div
            key="roadmap-content"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.6 }}
            className="relative z-10 max-w-2xl mx-auto w-full p-6"
          >
            <div className="bg-white/80 dark:bg-white/[0.03] backdrop-blur-xl dark:backdrop-blur-[24px] border border-slate-200 dark:border-white/[0.08] shadow-sm dark:shadow-[inset_0_1px_1px_rgba(255,255,255,0.05),0_8px_32px_rgba(0,0,0,0.4)] rounded-[2rem] overflow-hidden">
              <AnimatePresence mode="wait">
                {!roadmap ? (
                  <motion.div key="form" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="p-8 sm:p-10 flex-1 flex flex-col">
                    <div className="flex items-center gap-4 mb-8">
                      <div className="bg-[#fec708] p-3 rounded-xl shadow-[0_0_20px_rgba(254,199,8,0.3)]">
                        <Sparkles className="w-6 h-6 text-black" />
                      </div>
                      <div>
                        <h3 className="text-xl font-black text-slate-900 dark:text-white">Longevity Roadmap</h3>
                        <p className="text-slate-500 dark:text-white/60 text-sm font-medium">Personalized health timeline</p>
                      </div>
                    </div>
                    
                    {error && (
                      <div className="mb-6 p-3 bg-red-50 text-red-600 dark:bg-red-500/20 dark:text-white backdrop-blur-md border border-red-200 dark:border-red-500/30 rounded-lg text-sm font-medium">
                        {error}
                      </div>
                    )}
                    
                    <form onSubmit={handleSubmit} className="flex-1 flex flex-col space-y-5">
                      <div className="grid grid-cols-2 gap-4">
                        <div>
                          <label className="block text-xs font-bold text-slate-500 dark:text-white/60 uppercase tracking-wider mb-2">Pet Name</label>
                          <input type="text" name="name" value={formData.name} onChange={handleInputChange} placeholder="e.g. Max" className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-white/[0.08] focus:ring-2 focus:ring-[#fec708] focus:bg-white dark:focus:bg-white/[0.08] outline-none bg-white/50 dark:bg-white/[0.03] backdrop-blur-md text-slate-900 dark:text-white placeholder:text-slate-400 dark:placeholder:text-white/40 transition-all shadow-sm" />
                        </div>
                        <div>
                          <label className="block text-xs font-bold text-slate-500 dark:text-white/60 uppercase tracking-wider mb-2">Species</label>
                          <select name="species" value={formData.species} onChange={handleInputChange} className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-white/[0.08] focus:ring-2 focus:ring-[#fec708] focus:bg-white dark:focus:bg-white/[0.08] outline-none bg-white/50 dark:bg-white/[0.03] backdrop-blur-md text-slate-900 dark:text-white transition-all shadow-sm dark:[&>option]:bg-neutral-900">
                            <option>Dog</option>
                            <option>Cat</option>
                            <option>Other</option>
                          </select>
                        </div>
                      </div>
                      
                      <div>
                        <label className="block text-xs font-bold text-slate-500 dark:text-white/60 uppercase tracking-wider mb-2">Breed</label>
                        <input type="text" name="breed" value={formData.breed} onChange={handleInputChange} placeholder="e.g. American Bully" className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-white/[0.08] focus:ring-2 focus:ring-[#fec708] focus:bg-white dark:focus:bg-white/[0.08] outline-none bg-white/50 dark:bg-white/[0.03] backdrop-blur-md text-slate-900 dark:text-white placeholder:text-slate-400 dark:placeholder:text-white/40 transition-all shadow-sm" />
                      </div>
                      
                      <div className="grid grid-cols-2 gap-4">
                        <div>
                          <label className="block text-xs font-bold text-slate-500 dark:text-white/60 uppercase tracking-wider mb-2">Age (Years)</label>
                          <input type="number" name="age" value={formData.age} onChange={handleInputChange} placeholder="e.g. 5" min="0" step="0.1" className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-white/[0.08] focus:ring-2 focus:ring-[#fec708] focus:bg-white dark:focus:bg-white/[0.08] outline-none bg-white/50 dark:bg-white/[0.03] backdrop-blur-md text-slate-900 dark:text-white placeholder:text-slate-400 dark:placeholder:text-white/40 transition-all shadow-sm" />
                        </div>
                        <div>
                          <label className="block text-xs font-bold text-slate-500 dark:text-white/60 uppercase tracking-wider mb-2">Known Issues</label>
                          <input type="text" name="issues" value={formData.issues} onChange={handleInputChange} placeholder="e.g. Joint pain" className="w-full px-4 py-3 rounded-xl border border-slate-200 dark:border-white/[0.08] focus:ring-2 focus:ring-[#fec708] focus:bg-white dark:focus:bg-white/[0.08] outline-none bg-white/50 dark:bg-white/[0.03] backdrop-blur-md text-slate-900 dark:text-white placeholder:text-slate-400 dark:placeholder:text-white/40 transition-all shadow-sm" />
                        </div>
                      </div>
                      
                      <button type="submit" disabled={loading} className="mt-auto w-full bg-gradient-to-r from-[#fec708] to-[#fec708] text-black py-4 rounded-xl font-bold flex justify-center items-center gap-2 shadow-[0_0_20px_rgba(254,199,8,0.4)] hover:scale-[1.02] active:scale-95 disabled:opacity-70 disabled:hover:scale-100 transition-all">
                        {loading ? (
                          <>
                            <Loader2 className="animate-spin w-5 h-5" /> Analyzing...
                          </>
                        ) : (
                          <>
                            Generate Profile <ArrowRight className="w-5 h-5" />
                          </>
                        )}
                      </button>
                    </form>
                  </motion.div>
                ) : (
                  <motion.div key="results" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="p-8 flex-1 flex flex-col gap-6">
                    {/* Header */}
                    <div className="flex justify-between items-start border-b border-slate-200 dark:border-white/[0.08] pb-4">
                      <div>
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#fec708]/20 text-[#fec708] text-xs font-bold mb-2 border border-[#fec708]/50 shadow-sm">
                          <Sparkles className="w-3 h-3" /> Roadmap Generated
                        </div>
                        <h2 className="text-2xl font-black text-slate-900 dark:text-white">{formData.name}'s Plan</h2>
                      </div>
                      <button onClick={resetForm} className="p-2 text-slate-500 dark:text-white/60 hover:text-slate-900 dark:hover:text-white bg-white/50 dark:bg-white/[0.03] backdrop-blur-md border border-slate-200 dark:border-white/[0.08] rounded-full hover:bg-white dark:hover:bg-white/[0.08] transition-all shadow-sm" title="Start Over">
                        <RefreshCw size={18} />
                      </button>
                    </div>
                    
                    <p className="text-sm text-left text-slate-700 dark:text-white bg-white/50 dark:bg-white/[0.03] backdrop-blur-xl dark:backdrop-blur-[24px] border border-slate-200 dark:border-white/[0.08] shadow-sm dark:shadow-[inset_0_1px_1px_rgba(255,255,255,0.05)] p-6 rounded-xl leading-relaxed">
                      {roadmap.introduction}
                    </p>
                    
                    {/* Timeline */}
                    <div>
                      <h4 className="font-bold flex items-center justify-center gap-2 mb-4 text-slate-900 dark:text-white text-center">
                        <Clock size={18} className="text-[#fec708]" /> Health Timeline
                      </h4>
                      <div className="relative space-y-4 pl-4">
                        {roadmap.timeline.map((item: any, i: number) => (
                          <div key={i} className="relative bg-white/80 dark:bg-white/[0.03] backdrop-blur-xl dark:backdrop-blur-[24px] border border-slate-200 dark:border-white/[0.08] shadow-sm dark:shadow-[inset_0_1px_1px_rgba(255,255,255,0.05)] p-6 rounded-xl ml-4">
                            {/* Timeline Node */}
                            <div className="absolute -left-[21px] top-6 w-2 h-2 rounded-full bg-[#fec708] shadow-[0_0_10px_rgba(254,199,8,0.8)]" />
                            
                            <div className="text-center mb-4">
                              <span className="text-xs font-bold text-[#fec708] uppercase tracking-wide">{item.ageRange}</span>
                              <h5 className="font-bold text-base mt-1 text-slate-900 dark:text-white">{item.focusArea}</h5>
                            </div>
                            <ul className="text-sm text-left text-slate-700 dark:text-white space-y-3">
                              {item.actionItems.map((act: string, j: number) => (
                                <li key={j} className="flex items-start gap-4">
                                  <div className="w-1.5 h-1.5 bg-slate-300 dark:bg-white/50 rounded-full mt-2 shrink-0" />
                                  <span className="text-left flex-1 leading-relaxed">{act}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        ))}
                      </div>
                    </div>
                    
                    {/* Diet & Care grids */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                      <div className="bg-white/80 dark:bg-white/[0.03] backdrop-blur-xl dark:backdrop-blur-[24px] border border-slate-200 dark:border-white/[0.08] shadow-sm dark:shadow-[inset_0_1px_1px_rgba(255,255,255,0.05)] p-6 rounded-xl">
                        <h4 className="font-bold flex items-center justify-center gap-2 mb-4 text-slate-900 dark:text-white text-center">
                          <Utensils size={18} className="text-[#fec708]" /> Diet & Nutrition
                        </h4>
                        <ul className="text-sm text-left text-slate-700 dark:text-white space-y-3">
                          {roadmap.dietaryAdvice.map((adv: string, i: number) => (
                            <li key={i} className="flex items-start gap-4">
                              <ShieldCheck className="w-5 h-5 mt-0.5 shrink-0 text-[#fec708]" />
                              <span className="text-left flex-1 leading-relaxed">{adv}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                      <div className="bg-white/80 dark:bg-white/[0.03] backdrop-blur-xl dark:backdrop-blur-[24px] border border-slate-200 dark:border-white/[0.08] shadow-sm dark:shadow-[inset_0_1px_1px_rgba(255,255,255,0.05)] p-6 rounded-xl">
                        <h4 className="font-bold flex items-center justify-center gap-2 mb-4 text-slate-900 dark:text-white text-center">
                          <HeartPulse size={18} className="text-[#fec708]" /> Preventative Care
                        </h4>
                        <ul className="text-sm text-left text-slate-700 dark:text-white space-y-3">
                          {roadmap.preventativeCare.map((care: string, i: number) => (
                            <li key={i} className="flex items-start gap-4">
                              <HeartPulse className="w-5 h-5 mt-0.5 shrink-0 text-[#fec708]" />
                              <span className="text-left flex-1 leading-relaxed">{care}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
