import React, { useState, useEffect } from 'react';
import { Sparkles, ArrowRight, Loader2, RefreshCw, Lock, Stethoscope } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { usePetProfile } from '../hooks/usePetProfile';
import { GoogleGenAI } from '@google/genai';
import Markdown from 'react-markdown';

const apiKey = import.meta.env.VITE_GEMINI_API_KEY;

const generateRoadmapText = async (formData: any) => {
  if (!apiKey) {
    throw new Error('Gemini API Key missing');
  }
  
  const ai = new GoogleGenAI({ apiKey });
  
  const prompt = `CRITICAL VETERINARY INSTRUCTION: The patient is a ${formData.species}. You are an expert veterinary AI. You must ONLY provide a health and longevity roadmap for a ${formData.species}. Under NO circumstances should you provide advice for a dog if the patient is a cat, or vice versa. Providing cross-species medical advice is dangerous and strictly prohibited.

You are an elite, autonomous veterinary research agent. Your task is to generate a deeply contextual, living health roadmap for a pet based on their specific profile, medical history, and surgical history. 
CRITICAL RULES: Formatting and Depth: NEVER provide generic checklists. Generate an in-depth longevity plan tailored *exclusively* for the provided pet context (e.g., ${formData.name}, ${formData.age}-year-old ${formData.breed} ${formData.species}) and surgical history. Use premium typography formatting, strictly using '1-3 Months', '3-6 Months', etc., instead of 'Months 1-3'. Ask ONE clarification question to the parent if critical data is missing.

Live Research: Use your Google Search tool to find the absolute latest veterinary best practices, studies, or nutritional guidelines relevant to this specific pet's condition. Research specifically based on the pet's history of: ${formData.medicalHistory || 'None'} and ${formData.surgicalHistory || 'None'}. Make sure to include proper citations and links at the absolute bottom of the roadmap under a 'Sources & Literature' section with valid external URLs so the pet parent can read the research themselves. Format the output in clean, professional Markdown.

Pet Profile:
Name: ${formData.name}
Species: ${formData.species}
Breed: ${formData.breed}
Age: ${formData.age} years old
Medical History/Issues: ${formData.medicalHistory || formData.issues || 'None reported'}
Surgical History: ${formData.surgicalHistory || 'None reported'}`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3.1-pro-preview',
      contents: prompt,
      config: {
        tools: [{ googleSearch: {} }]
      }
    });

    return response.text || "Failed to generate roadmap.";
  } catch (error: any) {
    console.error("Error generating roadmap:", error);
    throw new Error(error.message || "Failed to generate roadmap.");
  }
};

export default function Roadmap() {
  const navigate = useNavigate();
  const { profile, loading: profileLoading } = usePetProfile();
  
  const isProfileIncomplete = !profile?.petName && !profile?.name;

  const [formData, setFormData] = useState({ 
    name: profile?.petName || profile?.name || '', 
    species: profile?.petType || 'Dog', 
    breed: profile?.breed || '', 
    age: profile?.age || '5', 
    issues: profile?.healthHistory || '',
    medicalHistory: profile?.medicalHistory || '',
    surgicalHistory: profile?.surgicalHistory || ''
  });
  const [loading, setLoading] = useState(false);
  const [roadmap, setRoadmap] = useState<string | null>(null);
  const [error, setError] = useState('');
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  useEffect(() => {
    if (!isProfileIncomplete && !roadmap && !loading && !hasAutoGenerated) {
      const autoGenerate = async () => {
        setLoading(true);
        setHasAutoGenerated(true);
        
        const currentData = {
          name: profile?.petName || profile?.name || '',
          species: profile?.petType || 'Dog',
          breed: profile?.breed || '',
          age: profile?.age || '5',
          issues: profile?.healthHistory || '',
          medicalHistory: profile?.medicalHistory || '',
          surgicalHistory: profile?.surgicalHistory || ''
        };
        setFormData(currentData);

        try {
          setRoadmap(await generateRoadmapText(currentData));
        } catch (err: any) {
          setError(err.message || 'Failed to generate roadmap.');
        } finally {
          setLoading(false);
        }
      };
      autoGenerate();
    }
  }, [isProfileIncomplete, roadmap, loading, hasAutoGenerated, profile]);

  const handleInputChange = (e: any) => setFormData(prev => ({ ...prev, [e.target.name]: e.target.value }));

  const handleSubmit = async (e: any) => {
    e.preventDefault();
    if (!formData.name || !formData.breed || !formData.age) return setError('Please fill in Name, Breed, and Age.');
    
    setError('');
    setLoading(true);
    
    const latestData = {
      ...formData,
      medicalHistory: profile?.medicalHistory || '',
      surgicalHistory: profile?.surgicalHistory || ''
    };
    
    try {
      setRoadmap(await generateRoadmapText(latestData));
    } catch (err: any) {
      setError(err.message || 'Failed to generate roadmap.');
    } finally {
      setLoading(false);
    }
  };

  const resetForm = () => {
    setRoadmap(null);
    setFormData({ 
      name: profile?.petName || profile?.name || '', 
      species: profile?.petType || 'Dog', 
      breed: profile?.breed || '', 
      age: profile?.age || '5', 
      issues: profile?.healthHistory || '',
      medicalHistory: profile?.medicalHistory || '',
      surgicalHistory: profile?.surgicalHistory || ''
    });
  };

  if (profileLoading) {
    return (
      <div className="h-full w-full flex flex-col items-center justify-center p-6 pb-32">
        <Loader2 className="w-10 h-10 text-[#fec708] animate-spin mb-4" />
        <p className="text-white/60 font-medium">Loading pet profile...</p>
      </div>
    );
  }

  if (isProfileIncomplete) {
    return (
      <div className="h-full w-full flex flex-col items-center justify-center p-6 pb-32">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="relative z-10 bg-white/80 dark:bg-white/[0.03] backdrop-blur-xl dark:backdrop-blur-[24px] border border-slate-200 dark:border-white/[0.08] shadow-sm dark:shadow-[inset_0_1px_1px_rgba(255,255,255,0.05),0_8px_32px_rgba(0,0,0,0.4)] rounded-[2rem] p-10 max-w-md w-full text-center flex flex-col items-center"
        >
          <div className="w-24 h-24 bg-[#fec708]/20 rounded-full flex items-center justify-center mb-6 shadow-[0_0_30px_rgba(254,199,8,0.3)] border border-[#fec708]/50">
            <Lock className="w-10 h-10 text-[#fec708]" />
          </div>
          <h2 className="font-heading font-extrabold text-2xl text-slate-900 dark:text-white mb-3">Profile Incomplete</h2>
          <p className="font-body font-medium text-slate-600 dark:text-slate-300 mb-8 leading-relaxed">
            A complete profile is required to unlock the personalized Longevity Roadmap for your pet.
          </p>
          <button 
            onClick={() => navigate('/settings')}
            className="w-full bg-gradient-to-r from-[#fec708] to-[#fec708] text-black py-4 rounded-xl font-bold shadow-[0_0_20px_rgba(254,199,8,0.4)] hover:scale-[1.02] active:scale-95 transition-all"
          >
            Update Profile
          </button>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="h-full w-full flex flex-col pb-32">
      <AnimatePresence>
        {loading && (
          <motion.div
            key="loading-overlay"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0, transition: { duration: 0.5 } }}
            className="flex flex-col items-center justify-center min-h-[75vh] px-6 py-12 relative overflow-hidden"
          >
            <div className="relative flex items-center justify-center mb-12">
              {/* Outer Aura */}
              <div className="absolute w-64 h-64 bg-yellow-500/10 rounded-full blur-[80px] animate-pulse"></div>
              {/* Inner Core */}
              <div className="absolute w-40 h-40 bg-white/10 rounded-full blur-[40px] animate-pulse" style={{ animationDelay: '0.5s' }}></div>
              {/* The Logo Container */}
              <div className="relative z-10 p-8 rounded-full bg-white/5 border border-white/10 backdrop-blur-2xl shadow-[0_0_50px_rgba(255,255,255,0.05)] flex flex-col items-center justify-center">
                <span className="text-white/90 font-extrabold text-xl tracking-widest text-center leading-tight">
                  PLANET<br/>ANIMAL
                </span>
              </div>
            </div>

            <div className="flex flex-col items-center space-y-2 z-10">
              <div className="flex items-center space-x-2 text-white/50 font-medium tracking-wide text-sm">
                <span>Powered by Google Gemini models</span>
                <span className="text-2xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-[#4285F4] via-[#EA4335] via-[#FBBC05] to-[#34A853] animate-pulse">G</span>
              </div>
              <p className="text-white/30 text-xs animate-pulse" style={{ animationDelay: '1s' }}>
                Synthesizing longevity research...
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
      <AnimatePresence mode="wait">
        <motion.div
          key="roadmap-content"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.6 }}
            className="relative z-10 max-w-2xl mx-auto w-full p-6"
          >
            <div className="bg-white/80 dark:bg-white/[0.03] backdrop-blur-xl dark:backdrop-blur-[24px] border border-slate-200 dark:border-white/[0.08] shadow-sm dark:shadow-[inset_0_1px_1px_rgba(255,255,255,0.05),0_8px_32px_rgba(0,0,0,0.4)] rounded-[2rem] overflow-hidden">
              <AnimatePresence mode="wait">
                {!roadmap ? (
                  <motion.div key="form" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="p-8 sm:p-10 flex-1 flex flex-col">
                    <div className="flex items-center gap-4 mb-8">
                      <div className="bg-[#fec708] p-3 rounded-xl shadow-[0_0_20px_rgba(254,199,8,0.3)]">
                        <Sparkles className="w-6 h-6 text-black" />
                      </div>
                      <div>
                        <h3 className="font-heading font-extrabold text-xl text-slate-900 dark:text-white">Longevity Roadmap</h3>
                        <p className="font-body font-medium text-slate-500 dark:text-slate-300 text-sm leading-relaxed">Personalized health timeline</p>
                      </div>
                    </div>
                    
                    {error && (
                      <div className="mb-6 p-3 bg-red-50 text-red-600 dark:bg-red-500/20 dark:text-white backdrop-blur-md border border-red-200 dark:border-red-500/30 rounded-lg text-sm font-medium">
                        {error}
                      </div>
                    )}
                    
                    <div className="flex-1 flex flex-col justify-center space-y-6">
                      <p className="font-body text-slate-600 dark:text-slate-300 text-center leading-relaxed">
                        Ready to generate a highly personalized health and longevity roadmap for <strong>{profile?.petName || profile?.name || 'your pet'}</strong> using advanced AI based on their specific breed and medical history?
                      </p>
                      
                      <button onClick={handleSubmit} disabled={loading} className="w-full bg-gradient-to-r from-[#fec708] to-[#fec708] text-black py-4 rounded-xl font-heading font-extrabold tracking-wide flex justify-center items-center gap-2 shadow-[0_0_20px_rgba(254,199,8,0.4)] hover:scale-[1.02] active:scale-95 disabled:opacity-70 disabled:hover:scale-100 transition-all">
                        Generate My Roadmap <ArrowRight className="w-5 h-5" />
                      </button>
                    </div>
                  </motion.div>
                ) : (
                  <motion.div key="results" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="p-8 flex-1 flex flex-col space-y-6">
                    {/* Header */}
                    <div className="flex justify-between items-start border-b border-slate-200 dark:border-white/[0.08] pb-6">
                      <div>
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#fec708]/20 text-[#fec708] text-xs font-bold mb-2 border border-[#fec708]/50 shadow-sm">
                          <Sparkles className="w-3 h-3" /> Roadmap Generated
                        </div>
                        <h2 className="font-heading font-extrabold text-2xl text-slate-900 dark:text-white">{formData.name}'s Plan</h2>
                      </div>
                      <button onClick={resetForm} className="p-2 text-slate-500 dark:text-white/60 hover:text-slate-900 dark:hover:text-white bg-white/50 dark:bg-white/[0.03] backdrop-blur-md border border-slate-200 dark:border-white/[0.08] rounded-full hover:bg-white dark:hover:bg-white/[0.08] transition-all shadow-sm" title="Start Over">
                        <RefreshCw size={18} />
                      </button>
                    </div>
                    
                    <div className="text-left text-slate-700 dark:text-white/90 leading-relaxed font-sans">
                      <Markdown
                        components={{
                          h1: ({node, ...props}) => <h1 className="font-heading font-extrabold text-2xl text-slate-900 dark:text-white mt-8 mb-4 tracking-tight" {...props} />,
                          h2: ({node, ...props}) => <h2 className="font-heading font-bold text-xl text-slate-900 dark:text-white mt-8 mb-3 tracking-tight border-b border-slate-200 dark:border-white/[0.08] pb-2" {...props} />,
                          h3: ({node, ...props}) => <h3 className="font-heading font-bold text-[#fec708] mt-6 mb-2 uppercase tracking-wide text-sm" {...props} />,
                          p: ({node, ...props}) => <p className="font-body text-base mb-4 text-slate-700 dark:text-slate-200 leading-relaxed" {...props} />,
                          ul: ({node, ...props}) => <ul className="list-disc pl-5 mb-4 space-y-2 opacity-90" {...props} />,
                          li: ({node, ...props}) => <li className="font-body text-slate-700 dark:text-slate-200" {...props} />,
                          strong: ({node, ...props}) => <strong className="font-bold text-slate-900 dark:text-white" {...props} />,
                          a: ({node, ...props}) => (
                            <a 
                              className="inline-flex items-center gap-1 font-medium text-[#fec708] hover:text-[#e5b307] bg-[#fec708]/10 hover:bg-[#fec708]/20 px-3 py-1 rounded-full text-sm transition-colors mt-1 break-all"
                              target="_blank" 
                              rel="noopener noreferrer" 
                              {...props} 
                            />
                          )
                        }}
                      >
                        {roadmap}
                      </Markdown>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          </motion.div>
      </AnimatePresence>
    </div>
  );
}
