import { ClinicalReview } from '../components/ClinicalCare';
import ClinicWallet from '../components/ClinicWallet';
import { onAuthStateChanged } from 'firebase/auth';
import { auth } from '../lib/firebase';
import StaffPrescriptions from '../components/StaffPrescriptions';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { careRequest } from '../lib/care/client';
import { careSummary, type CareState, type PilotConfig, type Role } from '../lib/care/domain';
import { careButton, careInput } from '../components/CareWorkflow';

export default function StaffCare() {
  const [session,setSession]=useState(auth.currentUser?.uid||'signed-out');
  useEffect(()=>onAuthStateChanged(auth,user=>setSession(user?.uid||'signed-out')),[]);
  return <StaffCareSession key={session}/>;
}
function StaffCareSession() {
  const [kind,setKind]=useState('scheduling'), [items,setItems]=useState<any[]>([]), [cursor,setCursor]=useState<string|null>(null), [role,setRole]=useState<Role>('parent');
  const [lookupUid,setLookupUid]=useState('');
  const [uid,setUid]=useState(''), [state,setState]=useState<CareState|null>(null), [config,setConfig]=useState<PilotConfig|null>(null), [stats,setStats]=useState<any>(null), [notice,setNotice]=useState(''), [busy,setBusy]=useState(false);
  const loadQueue=async(next?:string)=>{try{const d=await careRequest(undefined,`?view=queue&kind=${kind}${next?'&cursor='+encodeURIComponent(next):''}`);setRole(d.role);setItems(d.items);setCursor(d.nextCursor);setNotice('');}catch(e){setNotice((e as Error).message);}};
  useEffect(()=>{void loadQueue();},[kind]);
  const loadAccount=async(owner=uid)=>{setBusy(true);try{const d=await careRequest(undefined,'?ownerUid='+encodeURIComponent(owner)); if(d.role==='parent')throw Error('Staff access required.');setState(d.state);setConfig(d.config);setStats(d.metrics);setUid(owner);setLookupUid(owner);setNotice('');}catch(e){setState(null);setNotice((e as Error).message);}finally{setBusy(false);}};
  const act=async(body:Record<string,unknown>)=>{setBusy(true);try{await careRequest({...body,ownerUid:uid});await loadAccount();await loadQueue();setNotice('Saved by the care service.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}};
  const fields=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();return Object.fromEntries(new FormData(event.currentTarget));};
  const date=(value:FormDataEntryValue|undefined)=>value?new Date(String(value)).getTime():null;
  return <main className="min-h-screen bg-[#071912] px-4 py-8 text-white"><div className="mx-auto max-w-6xl">
    <Link to="/" className="text-[#fec708]">← Parent app</Link><h1 className="mt-5 font-heading text-3xl font-black">Care team workspace</h1><p className="mt-2 text-sm text-white/70">Recorded instructions, follow-ups and verified care. Access is checked by the server.</p>
    {notice && <p role="status" className="my-4 rounded-xl border border-[#fec708]/30 p-3">{notice}</p>}
    {role!=='parent' && <>
      {role==='veterinarian'&&<Link to="/doctor" className="my-4 block text-[#fec708] underline">Open doctor portal</Link>}{uid && <ClinicWallet ownerUid={uid} staff />}
      <div className="my-5 flex flex-wrap gap-2">{[['scheduling','Needs scheduling'],['missed','Missed / unresolved follow-up'],['clinical','Needs clinical review']].map(([key,label])=><button key={key} aria-pressed={kind===key} className={careButton} onClick={()=>setKind(key)}>{label}</button>)}</div>
      <p className="text-xs text-white/65">Up to 50 open items per page. Queue counts are not hospital-wide outcome claims.</p>
      <div className="my-4 grid gap-3 md:grid-cols-2">{items.map(q=><button key={q.recordId} className="rounded-2xl border border-white/15 bg-black/30 p-4 text-left" onClick={()=>void loadAccount(q.ownerUid)}><p className="font-bold">{q.kind} · {q.status}</p><p className="mt-1 text-sm break-all">Account {q.ownerUid} · Pet {q.petId}</p><p className="mt-2 text-sm">{q.nextAction}</p><p className="mt-2 text-xs text-white/65">Owner: {q.owner || 'Unassigned'}</p></button>)}</div>
      {!items.length && <p>No open items in this queue.</p>}{cursor&&<button className={careButton} onClick={()=>void loadQueue(cursor)}>Next 50 items</button>}
      <form className="my-5 flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();void loadAccount(lookupUid);}}><label className="flex-1 text-sm">Parent account UID<input className={careInput} value={lookupUid} onChange={e=>setLookupUid(e.target.value)} required/></label><button className={careButton} disabled={busy}>Open care record</button></form>
      {state&&<section className="rounded-2xl border border-white/15 bg-black/30 p-5"><h2 className="text-xl font-bold">Shared care record</h2>
        {stats&&<p className="mt-2 text-sm">This account: {stats.completedInWindow}/{stats.due} due milestones completed in the approved window · {stats.petsWithDatedNextStep}/{stats.pets} pets have a dated next step · {stats.unresolved} unresolved items · {stats.awards} awards / {stats.uniqueAwards} unique.</p>}
        <button className={`${careButton} mt-3`} disabled={busy} onClick={()=>void act({type:'tick'})}>Refresh follow-up queues</button>
        {state.pets.map(p=><p key={p.id} className="mt-3 text-sm"><strong>{p.name}:</strong> {careSummary(state,p.id)}</p>)}
        {role === 'veterinarian' && state.pets.map(p=><div key={p.id}><h3 className="mt-5 text-lg font-bold">{p.name} · Clinical analysis</h3><ClinicalReview ownerUid={state.ownerUid} petId={p.id}/></div>)}<StaffPrescriptions key={uid} state={state} config={config} role={role} busy={busy} act={act}/>{state.updates.map(u=><p key={u.id} className="mt-3 rounded-xl border border-white/10 p-3 text-sm">Parent update · {u.petId} · {new Date(u.createdAt).toLocaleString()}: {u.text}</p>)}
        {state.queues.filter(q=>q.status==='open').map(q=><form key={q.id} className="mt-4 rounded-xl border border-white/15 p-3" onSubmit={e=>{const f=fields(e);void act({type:'queue',queueId:q.id,nextAction:f.nextAction,resolve:f.resolve==='on'});}}><p>{q.kind} · Owner: {q.owner||'Unassigned'}</p><label className="mt-2 block text-sm">Next action / resolution<input className={careInput} name="nextAction" required maxLength={500} defaultValue={q.nextAction}/></label><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" name="resolve" disabled={q.kind==='clinical'&&role!=='veterinarian'}/>Resolve (clinical review requires a veterinarian)</label><button className={`${careButton} mt-2`} disabled={busy}>Assign to me and save</button></form>)}
        {state.milestones.map(m=><article key={m.id} className="mt-5 rounded-xl border border-white/15 p-4"><h3 className="font-bold">{m.title} · {m.status}</h3><p className="mt-2 text-sm">{m.instructions}</p><p className="mt-2 text-xs text-white/65">Source: {m.sourceRef} · Pet {m.petId} · Booking {m.booking.status} · {m.rule.points} points after verification</p>
          {m.status==='approved'&&<>
            {m.booking.status==='requested'&&<form className="mt-3 space-y-2" onSubmit={e=>{const f=fields(e);void act({type:'confirmBooking',petId:m.petId,milestoneId:m.id,reference:f.reference,scheduledAt:date(f.scheduledAt)});}}><p className="text-sm">Requested: {new Date(m.booking.requestedFor!).toLocaleString()}. First complete the booking in the clinic's booking system.</p><label className="block text-sm">Successful booking reference<input name="reference" className={careInput} required/></label><label className="block text-sm">Confirmed date/time<input name="scheduledAt" type="datetime-local" className={careInput} required/></label><button className={careButton} disabled={busy}>Record successful clinic booking</button></form>}
            <form className="mt-4 space-y-2" onSubmit={e=>{const f=fields(e);void act({type:'complete',petId:m.petId,milestoneId:m.id,evidence:f.evidence,completedAt:date(f.completedAt)});}}><label className="block text-sm">Unique performed-service record / bill line reference<input name="evidence" className={careInput} required/></label><label className="block text-sm">Actual completion date/time<input name="completedAt" type="datetime-local" className={careInput} required/></label><button className={careButton} disabled={busy}>Verify performed care and award once</button></form>
            {m.booking.status==='confirmed'&&<button className={`${careButton} mt-3`} disabled={busy} onClick={()=>void act({type:'missed',petId:m.petId,milestoneId:m.id})}>Record missed attendance</button>}
            <form className="mt-3 flex flex-wrap gap-2" onSubmit={e=>{const f=fields(e);void act({type:role==='veterinarian'&&f.exempt==='on'?'exempt':'bookingFailed',petId:m.petId,milestoneId:m.id,reason:f.reason});}}><label className="flex-1 text-sm">Booking failure / exemption reason<input className={careInput} name="reason" required/></label>{role==='veterinarian'&&<label className="text-sm"><input type="checkbox" name="exempt"/>Vet exemption</label>}<button className={careButton} disabled={busy}>Save reason</button></form>
          </>}
        </article>)}
        {role==='veterinarian'&&<form className="mt-6 space-y-3 border-t border-white/15 pt-5" onSubmit={e=>{const f=fields(e);void act({type:'approve',id:String(f.id),petId:f.petId,title:f.title,instructions:f.instructions,sourceRef:f.sourceRef,ruleId:f.ruleId,windowStart:date(f.windowStart),dueAt:date(f.dueAt),reminderAt:date(f.reminderAt)});}}><h3 className="font-bold">Approve one recorded milestone</h3><p className="text-xs">Copy dates and instructions from the clinical record. Leave unknown dates empty; the coordinator will obtain them.</p><label className="block text-sm">Stable clinical milestone ID<input className={careInput} name="id" required pattern="[A-Za-z0-9_-]+"/></label><label className="block text-sm">Pet<select name="petId" className={careInput}>{state.pets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{[['title','Milestone title'],['sourceRef','Clinical record reference']].map(([name,label])=><label key={name} className="block text-sm">{label}<input name={name} className={careInput} required/></label>)}<label className="block text-sm">Recorded clinical instructions<textarea name="instructions" className={careInput} required/></label>{[['windowStart','Approved window starts'],['dueAt','Approved due date'],['reminderAt','Approved reminder time']].map(([name,label])=><label key={name} className="block text-sm">{label}<input name={name} type="datetime-local" className={careInput}/></label>)}<label className="block text-sm">Hospital-approved reward rule<select className={careInput} name="ruleId" required>{Object.entries(config?.rules||{}).map(([key,r])=><option key={key} value={key}>{key}: {r.points} points / ₹{r.creditPaise/100}</option>)}</select></label><button className={careButton} disabled={busy || !config}>Approve recorded milestone</button></form>}
      </section>}
      {role==='manager'&&<details className="mt-6 rounded-2xl border border-white/15 p-4"><summary>Approve pilot configuration / process due queues</summary><form className="mt-3 space-y-3" onSubmit={e=>{const f=fields(e);void act({type:'configure',config:{version:f.version,workflowName:f.workflowName,rules:{[String(f.ruleId)]:{points:Number(f.points),creditPaise:Number(f.creditPaise)}}}});}}>{[['version','New immutable version'],['workflowName','Hospital-approved workflow name'],['ruleId','Reward rule ID'],['points','Points per verified eligible completion'],['creditPaise','Clinic credit in integer paise']].map(([name,label])=><label key={name} className="block text-sm">{label}<input className={careInput} name={name} type={['points','creditPaise'].includes(name)?'number':'text'} min="0" step="1" required/></label>)}<button className={careButton} disabled={busy}>Approve versioned rule</button></form><button className={`${careButton} mt-4`} onClick={async()=>{try{const r=await careRequest({type:'runDueJobs'});setNotice(`Processed ${r.processed} accounts. ${r.nextCursor?'More accounts remain; run the documented paginated job.':'Batch complete.'}`);}catch(e){setNotice((e as Error).message);}}}>Process first 100 due accounts</button></details>}
    </>}
  </div></main>;
}
