import { useEffect, useRef, useState } from 'react';
import { auth } from '../lib/firebase';
import { onAuthStateChanged } from 'firebase/auth';
export async function walletRequest(body?:Record<string,unknown>,ownerUid?:string) {
 const user=auth.currentUser;if(!user)throw new Error('Sign in to view your clinic wallet.');
 const r=await fetch('/api/wallet'+(ownerUid?'?ownerUid='+encodeURIComponent(ownerUid):''),{method:body?'POST':'GET',headers:{Authorization:`Bearer ${await user.getIdToken()}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
 if(!r.headers.get('content-type')?.includes('application/json'))throw new Error('Wallet service unavailable. Your existing points are unchanged.');
 const d=await r.json();if(auth.currentUser?.uid!==user.uid)throw new Error('Account changed. Reopen the wallet.');if(!r.ok)throw new Error(d.error||'Wallet request failed.');return d;
}
const field='block w-full min-w-0 rounded-xl border border-white/20 bg-black/20 p-3 mt-1';
export default function ClinicWallet({ownerUid,staff=false}:{ownerUid?:string;staff?:boolean}) {
 const [session,setSession]=useState(auth.currentUser?.uid);useEffect(()=>onAuthStateChanged(auth,u=>setSession(u?.uid)),[]);
 return <WalletSession key={`${session}:${ownerUid}`} ownerUid={ownerUid} staff={staff}/>;
}
function WalletSession({ownerUid,staff}:{ownerUid?:string;staff:boolean}) {
 const [data,setData]=useState<any>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[invoice,setInvoice]=useState(''),[points,setPoints]=useState(''),[reference,setReference]=useState(''),[eligible,setEligible]=useState(''),[plan,setPlan]=useState('essential'),[start,setStart]=useState(''),[end,setEnd]=useState('');const mounted=useRef(true),reservation=useRef({fingerprint:'',id:''});
 const load=async()=>{try{const d=await walletRequest(undefined,ownerUid);if(mounted.current){setData(d);setNotice('');}}catch(e){if(mounted.current)setNotice((e as Error).message);}};
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;};},[]);
 const run=async(b:Record<string,unknown>)=>{setBusy(true);try{const result=await walletRequest({...b,...(ownerUid?{ownerUid}:{})});if(mounted.current){await load();setNotice(result.invoiceId?'Invoice registered. Give the parent this ID: '+result.invoiceId:'Recorded by the wallet service.');}}catch(e){if(mounted.current)setNotice((e as Error).message);}finally{if(mounted.current)setBusy(false);}};
 return <section aria-label="Clinic wallet" className="relative z-10 rounded-2xl border border-white/15 bg-black/30 p-5 my-5 text-white">
  <h2 className="cinematic-card-title text-2xl">Pawl · Your clinic wallet</h2>
  {data&&<><div className="grid sm:grid-cols-3 gap-4 my-4"><p><strong className="block text-2xl text-planet-yellow">{data.wallet?data.wallet.points-data.wallet.reservedPoints:'Not reconciled'}</strong><span className="text-sm">Available points</span></p><p><strong className="block text-2xl">{data.pendingPoints}</strong><span className="text-sm">Pending confirmed care</span></p><p><strong className="block text-2xl">{data.wallet?.reservedPoints||0}</strong><span className="text-sm">Reserved for a clinic invoice</span></p></div>
  {!data.wallet?.legacyReconciled&&<p className="text-sm text-planet-yellow">Previous profile balance: {data.legacyPoints===null?'not recorded':data.legacyPoints+' points'}. Kept unchanged until the clinic reconciles it with the ledger.</p>}
  <p className="text-xs leading-relaxed text-white/75 mt-3">1 point = ₹0.25 clinic discount. Up to 10% of an eligible invoice, ₹250 per invoice and ₹1,000 per calendar month (UTC). Booking points become spendable after staff verifies completed care. Checkup entitlements are separate; points are not cash.</p>
  {!staff&&<details className="mt-4"><summary className="cursor-pointer font-semibold">Use points at the hospital</summary><p className="text-sm mt-3">Ask billing staff for the invoice ID. Reserve points here, then staff confirms the actual invoice discount. A reservation lasts 15 minutes; release it if unused.</p><label className="block text-sm mt-3">Invoice ID<input className={field} value={invoice} onChange={e=>setInvoice(e.target.value)}/></label><label className="block text-sm mt-3">Points to use<input type="number" min="1" step="1" className={field} value={points} onChange={e=>setPoints(e.target.value)}/></label><button disabled={busy||!invoice||!points} className="mt-3 rounded-xl bg-planet-yellow text-black p-3 font-semibold disabled:opacity-40" onClick={()=>{const fingerprint=invoice+':'+points;if(reservation.current.fingerprint!==fingerprint)reservation.current={fingerprint,id:crypto.randomUUID()};void run({type:'reserve',id:reservation.current.id,invoiceId:invoice,points:Number(points)});}}>Reserve invoice discount</button></details>}
  {staff&&<details className="mt-4"><summary className="cursor-pointer font-semibold">Billing controls</summary><label className="block text-sm mt-3">Actual invoice / billing adjustment reference<input className={field} value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="block text-sm mt-3">Eligible invoice amount in paise<input type="number" min="1" step="1" className={field} value={eligible} onChange={e=>setEligible(e.target.value)}/></label><button disabled={busy||!reference||!eligible} className="mt-3 border border-planet-yellow/40 rounded-xl p-3" onClick={()=>void run({type:'registerInvoice',reference,eligiblePaise:Number(eligible)})}>Record confirmed invoice</button>{data.role==='manager'&&!data.wallet?.legacyReconciled&&<button disabled={busy||data.legacyPoints===null} className="block mt-3 border border-white/30 rounded-xl p-3" onClick={()=>void run({type:'reconcileLegacy',expectedPoints:data.legacyPoints})}>Manager: reconcile displayed legacy balance</button>}{data.role==='manager'&&<div className="border-t border-white/15 pt-3 mt-4"><h3 className="font-semibold">Verify paid membership</h3><p className="text-xs mt-2">Enter its actual payment receipt above. Existing reward snapshots stay unchanged.</p><label className="block text-sm mt-3">Plan<select className={field} value={plan} onChange={e=>setPlan(e.target.value)}><option value="essential">Essential</option><option value="advanced">Advanced</option><option value="prestige">Premium</option></select></label><label className="block text-sm mt-3">Paid period begins<input type="datetime-local" className={field} value={start} onChange={e=>setStart(e.target.value)}/></label><label className="block text-sm mt-3">Paid period ends<input type="datetime-local" className={field} value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="mt-3 border border-planet-yellow/40 rounded-xl p-3" disabled={busy||!reference||!start||!end} onClick={()=>void run({type:'verifySubscription',plan,status:'active',paymentReference:reference,startsAt:new Date(start).getTime(),endsAt:new Date(end).getTime()})}>Confirm verified payment</button><button className="block mt-3 underline" disabled={busy||!reference||!start||!end} onClick={()=>void run({type:'verifySubscription',plan,status:'cancelled',paymentReference:reference,startsAt:new Date(start).getTime(),endsAt:new Date(end).getTime()})}>Record cancellation of this membership</button></div>}</details>}
  {data.wallet?.reconciliationRequired&&<p role="alert" className="mt-3 text-sm text-planet-yellow">A refunded reward needs clinic reconciliation. Your other history is retained; new redemptions are paused.</p>}
  {data.reservations.map((r:any)=><div key={r.id} className="mt-3 border border-white/15 rounded-xl p-3 text-sm"><p>{r.points} points reserved · ID {r.id}</p><p>Expires {new Date(r.expiresAt).toLocaleString()}</p><button disabled={busy} className="underline mt-2" onClick={()=>void run({type:'release',id:r.id})}>Release reservation</button>{staff&&<button disabled={busy||!reference} className="block underline mt-2 text-planet-yellow" onClick={()=>void run({type:'apply',id:r.id,billingReference:reference})}>Confirm discount applied to the invoice</button>}</div>)}
  <details className="mt-4"><summary className="cursor-pointer text-sm">Latest wallet activity</summary>{data.entries.map((e:any)=><p key={e.id} className="mt-2 text-xs">{e.type} · {e.points??'—'} points · {new Date(e.at).toLocaleString()}{e.convertible===false?' · Needs conversion reconciliation':''}{staff&&data.role==='manager'&&e.status==='reconciliation-required'&&<button className="block underline mt-1" disabled={busy} onClick={()=>void run({type:'settleRefund',id:e.id})}>Settle this refunded reward from available points</button>}{staff&&e.type==='earn'&&e.convertible===true&&<button className="block underline mt-1" disabled={busy||!reference} onClick={()=>void run({type:'reverseEarn',entryId:e.id,billingReference:reference})}>Record verified service refund</button>}{staff&&e.type==='apply'&&<button className="block underline mt-1" disabled={busy||!reference} onClick={()=>void run({type:'reverse',id:e.id.replace('apply-',''),billingReference:reference})}>Reverse confirmed invoice discount</button>}</p>)}</details></>}
  {notice&&<p role="status" className="mt-3 text-sm text-planet-yellow break-words">{notice}</p>}<button onClick={()=>void load()} className="mt-3 underline text-sm" disabled={busy}>Refresh wallet</button>
 </section>;
}
