import { useEffect, useRef, useState } from 'react';
import { useCare } from '../lib/care/client';
import { prescriptionRequest, prescriptionSource } from '../lib/care/prescription-client';
import { blankTranscript, type Prescription, type Transcript } from '../lib/care/prescriptions';
import { careButton, careInput } from './CareWorkflow';

export const transcriptionLabels = {petName:'Pet name on prescription',medications:'Written medication names, doses and timing',instructions:'Written follow-up instructions',followUp:'Written follow-up date or timing'};
export function SourcePreview({rx,ownerUid,source=prescriptionSource}:{rx:Prescription;ownerUid:string;source?:typeof prescriptionSource}) {
  const [url,setUrl]=useState(''),[error,setError]=useState('');
  useEffect(()=>{let active=true,objectUrl='';setUrl('');setError('');void source(rx.id,ownerUid).then(blob=>{if(active){objectUrl=URL.createObjectURL(blob);setUrl(objectUrl);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[rx.id,ownerUid,source]);
  return url?<a href={url} target="_blank" rel="noreferrer"><img src={url} alt="Original prescription source — open full size" className="my-3 max-h-72 w-full rounded-xl bg-white object-contain"/></a>:<p role="status" className="my-3 text-sm">{error||'Loading private original…'}</p>;
}
export function TranscriptFields({value,onChange}:{value:Transcript;onChange:(v:Transcript)=>void}) {
  return <div className="space-y-4">{Object.entries(transcriptionLabels).map(([key,label])=>{const k=key as keyof Transcript,r=value[k];return <fieldset key={key} className="min-w-0"><legend className="text-sm font-bold">{label}</legend><label className="mt-1 block text-xs">Transcription (leave blank if unknown)<textarea className={`${careInput} mt-1`} aria-label={label} maxLength={1600} value={r.value||''} onChange={e=>onChange({...value,[k]:{...r,value:e.target.value||null,confidence:'low'}})}/></label><div className="mt-1 flex flex-wrap items-center gap-2"><span className="text-xs text-[#ffe28f]">{r.confidence} reading confidence · not clinical approval</span></div><p className="mt-1 break-words text-xs text-white/60">Original extraction quote: {r.sourceQuote||'Not readable / not recorded'}</p></fieldset>;})}</div>;
}
export default function PrescriptionWorkspace({request=prescriptionRequest,source=prescriptionSource}:{request?:typeof prescriptionRequest;source?:typeof prescriptionSource}) {
  const {state,petId,setPetId,command,refresh,error,loading}=useCare();
  // Parent component is keyed by account and pet: pending UI never moves to another record.
  const [selected,setSelected]=useState<string|null>(null),[draft,setDraft]=useState<Transcript>(blankTranscript),[association,setAssociation]=useState(petId);
  const [file,setFile]=useState<File|null>(null),[localPreview,setLocalPreview]=useState(''),[consent,setConsent]=useState(false),[confirmed,setConfirmed]=useState(false);
  const [busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[notice,setNotice]=useState(''),[settings,setSettings]=useState<{retentionDays:number;ocrConfigured:boolean}|null>(null);
  const active=useRef(true),dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{active.current=true;void request(undefined,'?view=settings').then(s=>{if(active.current)setSettings(s);}).catch(e=>{if(active.current)setNotice(e.message);});return()=>{active.current=false;};},[request]);
  useEffect(()=>{if(!file){setLocalPreview('');return;}const url=URL.createObjectURL(file);setLocalPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);setNotice('');try{await fn();}catch(e){if(active.current)setNotice((e as Error).message);}finally{if(active.current)setBusy(false);}};
  const records=state?.prescriptions?.filter(r=>r.petId===petId)||[],rx=state?.prescriptions?.find(r=>r.id===selected);
  const open=(record:Prescription)=>{setNotice('');setSelected(record.id);setDraft(structuredClone(record.versions.at(-1)?.transcript||record.extraction||blankTranscript()));setAssociation(record.petId);setConfirmed(false);dialog.current?.showModal();};
  const upload=()=>run(async()=>{
    if(!file||!consent||!state)return;
    if(!['image/png','image/jpeg'].includes(file.type)||file.size>2*1024*1024)throw new Error('Choose a PNG or JPEG up to 2 MB.');
    const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read this image.'));reader.readAsDataURL(file);});
    setProgress(0);const result=await request({type:'upload',petId,consent,base64,mime:file.type},'',n=>{if(active.current)setProgress(n);});
    await refresh();if(active.current){setNotice(result.duplicate?'This source is already saved. Open it below to review or correct it.':'Source saved privately. Review the transcription below; clinical approval is still pending.');setFile(null);setConsent(false);}
  });
  return <section aria-label="Private prescriptions" className="my-4 min-w-0 rounded-2xl border border-white/15 bg-[#071912] p-4 text-white">
    <h2 className="font-heading text-lg font-bold">One prescription. Shared care.</h2><p className="mt-2 text-sm text-white/70">Pritpawl organizes recorded instructions. Pawlina follows approved dates. Pawl rewards staff-verified care.</p>
    {loading?<p role="status">Loading care record…</p>:error||!state?<p role="alert" className="mt-3">{error||'Sign in to use prescriptions.'}</p>:<>
      <label className="mt-3 block text-sm">Associate with pet<select aria-label="Prescription pet" className={`${careInput} mt-1`} value={petId} disabled={busy} onChange={e=>setPetId(e.target.value)}>{state.pets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
      <p className="mt-3 text-xs text-white/70">PNG or JPEG · up to 2 MB / 16 megapixels. Unclear names, doses and dates stay uncertain. Parent confirmation never approves treatment.</p>
      <label className="mt-3 block text-sm">Prescription image<input aria-label="Prescription image" className="mt-2 block w-full min-w-0 text-xs file:mr-2 file:rounded-lg file:border-0 file:bg-[#fec708] file:px-3 file:py-2 file:text-black" type="file" accept="image/png,image/jpeg" disabled={busy||!settings} onChange={e=>{setFile(e.target.files?.[0]||null);setConsent(false);setProgress(0);}}/></label>
      {localPreview&&<img src={localPreview} alt="Selected image, not yet uploaded" className="mt-3 max-h-48 w-full rounded-xl bg-white object-contain"/>}
      <label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={consent} disabled={busy||!settings} onChange={e=>setConsent(e.target.checked)}/>I consent to private storage and hospital review{settings?.ocrConfigured?' and Gemini transcription':''} for this pet. {settings?`The source is accessible for ${settings.retentionDays} days.`:'Storage configuration is unavailable.'}</label>
      <p className="mt-2 text-xs text-white/65">You can delete the image and transcription here. A minimal audit and already approved clinical / reward records are retained by the clinic. {settings&&!settings.ocrConfigured?'OCR is not configured; manual transcription will be available after upload.':''}</p>
      <button className={`${careButton} mt-3`} disabled={busy||!file||!consent||!settings||!state.pets.some(p=>p.id===petId)} onClick={()=>void upload()}>{busy?'Saving…':'Upload / retry image'}</button>
      {busy&&file&&<div role="status" className="mt-3 text-sm"><progress aria-label="Image upload progress" className="w-full accent-[#fec708]" value={progress} max={100}/>{progress<100?`Uploading ${progress}%`:'Image sent. Saving and reading the source…'}</div>}
      <div className="mt-4 space-y-3">{records.map(r=><article key={r.id} className="rounded-xl border border-white/15 p-3"><p className="text-sm font-bold">Prescription · {new Date(r.createdAt).toLocaleDateString()} · {r.status==='confirmed'?'Transcription confirmed; see care plan for approval':r.status}</p><p className="mt-1 text-xs text-white/65">Version {r.revision} · {r.ocrStatus==='unavailable'?'OCR unavailable — enter text from original':r.ocrStatus==='ready'?'OCR reading needs review':'Upload pending — retry same image'} · Source expires {new Date(r.expiresAt).toLocaleDateString()}</p>{r.status!=='deleted'&&r.status!=='uploading'&&<button className={`${careButton} mt-2`} onClick={()=>open(r)}>Review source / correct pet</button>}{(r.status==='deleted'||r.status==='uploading')&&<button className={`${careButton} mt-2`} disabled={busy} onClick={()=>void run(async()=>{await request({type:'delete',prescriptionId:r.id,expectedRevision:r.revision});setNotice('Source deletion completed.');})}>{r.status==='uploading'?'Delete pending upload':'Retry storage deletion'}</button>}</article>)}</div>
    </>}
    {notice&&<p role="status" className="mt-3 text-sm text-[#ffe28f]">{notice}</p>}
    <dialog aria-label="Review prescription transcription" ref={dialog} onCancel={e=>{if(busy)e.preventDefault();}} className="hide-scrollbar m-auto max-h-[90dvh] w-[calc(100%-2rem)] max-w-lg overflow-y-auto rounded-2xl border border-white/20 bg-[#071912] p-4 text-white backdrop:bg-black/70">
      {rx&&<><h2 className="text-lg font-bold">Review original and transcription</h2><p className="mt-2 text-xs">Source {rx.hash.slice(0,12)} · version {rx.revision}. Compare against the original. Leave unknown fields empty.</p><SourcePreview rx={rx} ownerUid={state!.ownerUid} source={source}/><label className="mb-3 block text-sm">Correct pet association<select className={careInput} value={association} onChange={e=>setAssociation(e.target.value)}>{state?.pets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><TranscriptFields value={draft} onChange={setDraft}/><label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked the transcription and pet association. This records my reading, not clinical approval.</label><p className="mt-2 text-xs text-white/65">Corrections stop pending care from older versions for vet review. The clinic must reconcile existing appointments. Completed rewards are preserved.</p>
      <div className="mt-4 flex flex-wrap gap-2"><button className={careButton} disabled={busy||!confirmed} onClick={()=>void run(async()=>{await command({type:'confirmPrescription',prescriptionId:rx.id,expectedRevision:rx.revision,petId:association,transcript:draft,consent:true});dialog.current?.close();setNotice('Transcription saved for source and conflict review. No treatment or date has been approved.');})}>Confirm transcription</button><button className={careButton} disabled={busy} onClick={()=>dialog.current?.close()}>Close</button></div>
      <details className="mt-4 text-sm"><summary>Delete source and transcription</summary><p className="mt-2">Deletion cannot be undone. Pending care based on this source stops for review. Clinical audit and completed rewards remain.</p><button className={`${careButton} mt-2`} disabled={busy} onClick={()=>void run(async()=>{await request({type:'delete',prescriptionId:rx.id,expectedRevision:rx.revision});await refresh();dialog.current?.close();setNotice('Source image and transcription deleted.');})}>Delete this source</button></details>{notice&&<p role="alert" className="mt-3 text-sm">{notice}</p>}</>}
    </dialog>
  </section>;
}
