import { prescriptionSource } from '../lib/care/prescription-client';
import { useState } from 'react';
import { type CareState, type PilotConfig, type Role } from '../lib/care/domain';
import { SourcePreview, transcriptionLabels } from './PrescriptionWorkspace';
import { careButton, careInput } from './CareWorkflow';
export default function StaffPrescriptions({state,config,role,busy,act,source=prescriptionSource}:{state:CareState;config:PilotConfig|null;role:Role;busy:boolean;source?:typeof prescriptionSource;act:(body:Record<string,unknown>)=>Promise<void>}) {
  const [open,setOpen]=useState<string|null>(null);
  return <section className="mt-5"><h3 className="font-bold">Source-linked prescription review</h3><p className="mt-2 text-xs text-white/65">All extracts and parent history are untrusted readings. Compare the original; resolve wrong-pet associations and conflicts before approval. Routine reminders then follow the approved plan.</p>
    {state.pets.map(p=>p.history&&<p key={p.id} className="mt-3 text-sm">{p.name} · Parent-reported: breed {p.history.breed}; allergies {p.history.allergies||'not provided'}; surgeries {p.history.surgeries||'not provided'}; chronic conditions {p.history.conditions||'not provided'}.</p>)}
    {(state.prescriptions||[]).map(rx=><article key={rx.id} className="mt-4 rounded-xl border border-white/15 p-3"><p className="font-bold">Pet {state.pets.find(p=>p.id===rx.petId)?.name} · {rx.status} · version {rx.revision}</p><p className="mt-1 text-xs break-all">Source SHA-256: {rx.hash}</p>{rx.status!=='deleted'&&<button className={`${careButton} mt-2`} onClick={()=>setOpen(open===rx.id?null:rx.id)}>Compare source and versions</button>}
      {open===rx.id&&rx.status!=='deleted'&&<><SourcePreview rx={rx} ownerUid={state.ownerUid} source={source}/>{rx.versions.map(v=><details key={v.version} open={v.version===rx.revision} className="mt-3"><summary>Parent transcription v{v.version} · Pet {v.petId} · {new Date(v.at).toLocaleString()}</summary>{Object.entries(transcriptionLabels).map(([k,label])=><p key={k} className="mt-2 whitespace-pre-wrap break-words text-sm"><strong>{label}:</strong> {v.transcript[k as keyof typeof v.transcript].value||'Not recorded / unreadable'} · {v.transcript[k as keyof typeof v.transcript].confidence} confidence</p>)}</details>)}
        {role==='veterinarian'&&rx.status==='confirmed'&&<form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const date=(v:FormDataEntryValue)=>v?new Date(String(v)).getTime():null;void act({type:'approve',id:`rx-${rx.id}-v${rx.revision}`,petId:rx.petId,prescriptionId:rx.id,prescriptionVersion:rx.revision,title:f.title,ruleId:f.ruleId,windowStart:null,dueAt:date(f.dueAt),reminderAt:date(f.reminderAt),sourceReviewed:f.sourceReviewed==='on',conflictsReviewed:f.conflictsReviewed==='on',conflictAction:f.conflictAction});}}><label className="block text-sm">Recorded follow-up title<input className={careInput} name="title" maxLength={160} required/></label><p className="text-xs text-white/65">Instructions come from this exact confirmed transcription. Ask the parent to correct it if inaccurate. No date in source means no clinical deadline.</p><label className="block text-sm">Explicit source follow-up date/time (leave empty if unknown)<input className={careInput} name="dueAt" type="datetime-local" disabled={!rx.versions.at(-1)?.transcript.followUp.value}/></label><label className="block text-sm">Approved reminder time (optional)<input className={careInput} name="reminderAt" type="datetime-local"/></label><label className="block text-sm">Approved eligibility / reward rule<select className={careInput} name="ruleId" required><option value="">Select appropriate documented care rule</option>{Object.entries(config?.rules||{}).map(([key,r])=><option key={key} value={key}>{key} · {r.points} points / ₹{r.creditPaise/100}</option>)}</select></label><label className="flex gap-2 text-sm"><input name="sourceReviewed" type="checkbox" required/>I compared the original source, pet identity and uncertain fields.</label><label className="block text-sm">Other active prescription steps<select className={careInput} name="conflictAction"><option value="">Choose if another source has active steps</option><option value="complementary">Keep — reviewed as complementary care</option><option value="replace">Replace other active prescription steps</option></select></label><p className="text-xs text-white/65">{state.milestones.filter(m=>m.petId===rx.petId&&m.status==='approved'&&m.prescription&&m.prescription.id!==rx.id).length} other active source-linked steps. Replacements stop reminders; reconcile their clinic bookings.</p><label className="flex gap-2 text-sm"><input name="conflictsReviewed" type="checkbox" required/>I reviewed other prescriptions and resolved conflicts. This care is clinically appropriate and eligible under the selected rule.</label><button className={careButton} disabled={busy||!config}>Approve this source version</button></form>}
      </>}
    </article>)}
  </section>;
}
