// Isolated synthetic fixture, excluded from deployment. No audio, API or patient data.
import {createRoot} from 'react-dom/client';
import {useEffect,useState} from 'react';
import {BrowserRouter,useNavigate,useLocation} from 'react-router-dom';
import ApprovedAdviceSpeech from './components/ApprovedAdviceSpeech';
import './index.css';
const engine=new EventTarget(); let voices:SpeechSynthesisVoice[]=[], current:SpeechSynthesisUtterance|undefined, plays=0,cancels=0;
Object.defineProperty(window,'speechSynthesis',{configurable:true,value:Object.assign(engine,{getVoices:()=>voices,cancel:()=>{cancels++;current=undefined;},speak:(value:SpeechSynthesisUtterance)=>{current=value;plays++;setTimeout(()=>{if(current===value)value.onstart?.({} as SpeechSynthesisEvent);},0);}})});
Object.defineProperty(window,'SpeechSynthesisUtterance',{configurable:true,value:class {text:string;constructor(text:string){this.text=text;}}});
function Review(){const navigate=useNavigate(),location=useLocation(),[version,setVersion]=useState(1),[show,setShow]=useState(true),[metrics,setMetrics]=useState('');useEffect(()=>{const t=setInterval(()=>setMetrics(`Plays ${plays}; cancels ${cancels}; active ${current?'yes':'no'}; viewport ${document.documentElement.clientWidth}; content ${document.documentElement.scrollWidth}`),100);return()=>clearInterval(t);},[]);return <main className="p-4 min-h-screen bg-[#071912] text-white"><h1>Synthetic speech review</h1><p>No audio or patient data. This checks controls with a simulated device.</p><p role="status">{metrics}</p><div className="flex flex-wrap gap-2 my-4">{[['Load local voice',()=>{voices=[{lang:'en-IN',name:'Synthetic local English',voiceURI:'synthetic-local',localService:true,default:true}];engine.dispatchEvent(new Event('voiceschanged'));}],['Change approved version',()=>setVersion(v=>v+1)],['Change route',()=>navigate(location.pathname==='/other'?'/':'/other')],['Toggle component',()=>setShow(s=>!s)],['Simulate failure',()=>current?.onerror?.({} as SpeechSynthesisErrorEvent)]] .map(([label,fn])=><button key={String(label)} className="border p-3 rounded-xl" onClick={fn as ()=>void}>{String(label)}</button>)}</div><p>Approved synthetic text version {version}: Please contact the clinic about your recorded appointment.</p>{show&&<ApprovedAdviceSpeech approvalId={'synthetic-'+version} text={'Approved synthetic text version '+version+': Please contact the clinic about your recorded appointment.'}/>}</main>}
createRoot(document.getElementById('root')!).render(<BrowserRouter><Review/></BrowserRouter>);
